### ISSUE TITLE
3rd postponement emails $30$

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#103]
E-mails to be sent as Peter Szczepaniak

ENG: Postponement of the E-commerce Berlin Expo 2022 / New date released
DE: Verschiebung der E-commerce Berlin Expo 2022 / Neues Datum veröffentlic
[Emails.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/7669575/Emails.zip)

(files in .zip, as GH doesn't support php files)

**Comment by jprzybylski4** [comment]
It would be great if we could send it around noon tomorrow. 

The date is final - there are no other good dates to choose from. 
However, FYI we don't have the contract signed just yet. We are in touch with Station Berlin.

**Comment by az** [comment]
@jprzybylski4 is PSZ set as event manager to all companies? I HAVE TOLD you how it works....so... considering that "E-mails to be sent as Peter Szczepaniak" is inadequate ....

**Comment by az** [comment]
sent
