### ISSUE TITLE
Stop showing past exhibitors on the website $60$

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#106]
We've lately received emails from companies below - they are not happy that we are confusing their customers claiming that they participate in the Expo. Especially since their profile shows the booth location as well. I know that it will be part of the new admin - I'm just submitting the issue to let you know. 

- Mondi Group - https://ecommerceberlin.com/exhibitors/mondigroupcom
- MySize - https://ecommerceberlin.com/exhibitors/mysizeidcom

**Comment by jprzybylski4** [comment]
+ email from today:
GlobalDots - https://ecommerceberlin.com/exhibitors/globaldotscom

**Comment by az** [comment]
@jprzybylski4 as you should recall we have displayed "profile archived" msg .... but as i can see it have just stopped working - i will inspect that

**Comment by jprzybylski4** [comment]
@az case of globaldots is getting more serious - they've just sent us a following email. Can we do something to delete their profile permanently? 

> Unfortunately, we have to get in touch with you for an unpleasant reason:
As we found out a few days ago and have already registered with you in the chat with Dominik, you are UNLAWFULLY using our and our partner´s name on your website as an advertisement for Ecommerce 2022.

The mention of our name, the use of our logo as well as that of our partner Akamai is a violation of the right to a name and personal rights according to § 12 BGB (German Civil Code), which is why you are or have become liable to prosecution at this point without our consent.
We see our provider-independent positioning as crucial to our success and your unauthorised use could damage our relationships with other providers.

We therefore set you a deadline until the end of the week to remove our logos, content as well as our name and that of our partner Akamai from your list of participants as well as from the hall plan or to make us a counter-proposal with compensation.

Attached you find the screenshots.

We expect a reply very soon.

**Comment by az** [comment]
globaldots - 1022
mondigroup - 1660
mysize - 1328

**Comment by az** [comment]
@jprzybylski4 i have removed them from the list on the homepage . in the future - when there is a request for total data removal why dont you just sign into company's panel and remove data?
