### ISSUE TITLE
3rd postponement email to visitors

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#108]
ENG: Postponement of the E-commerce Berlin Expo 2022 / New date released
DE: Verschiebung der E-commerce Berlin Expo 2022 / Neues Datum veröffentlic
[Visitors_email.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/7686991/Visitors_email.zip)

**Comment by az** [comment]
@jprzybylski4 emails to visitors are handled differently  than to the exhibitors- we cannot send de and en - i will merge 2 versions together (in the farer future we may change it )

**Comment by jprzybylski4** [comment]
Just a reminder - would be great if we could send it tomorrow around noon

**Comment by az** [comment]
@jprzybylski4 the best would be to send it via admin - PLEASE DO IT . i cannot see any benefits from sending it via console. (especially that we should omit newest registrations and it is possible only via admin - https://pages.ecommerceberlin.com/admin/filtered?tags=visitor&until=20211206 )
