### ISSUE TITLE
Chatlio hasn't turned on automatically today $45$

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#114]
title
Chatlio hasn't turned on automatically today at 9:00 am

environment 
tested on chrome 

expected result
chatlio is supposed to work automatically - 9:00am - 5:15 pm

actual result
chatlio was in the offline mode - asking for the email for further contact

steps to reproduce
n/a

proof
chat received at 11am in the offline mode
![Slack | support_berlin | fp20 2022-01-31 11-43-32](https://user-images.githubusercontent.com/75311923/151779875-8e4bf270-7c0b-47ce-9d26-d27c22ddf6b8.png)

Severity/Priority
Minor

number of users already affected (reporting this issue) of total users
1

team members who tested (apart from creator of bug report)
MM & DK

**Comment by az** [comment]
@jprzybylski4 im switching off the presence detection - we will see how things will perform
