### ISSUE TITLE
(EMAIL) Exhibitors Manual emails $30$

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#119]
Please schedule and send the attached emails.
I'd appreciate it if you could double-check if I've linked the files and created the buttons correctly, as had to use StackOverflow for that. 

Subject ENG: E-commerce Berlin Expo 2022 - How is your preparation going on?
Subject DE: E-commerce Berlin Expo 2022 - Wie geht eure Vorbereitung voran? 

[ebe6-logistics-manual-emails.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/7997042/ebe6-logistics-manual-emails.zip)

**Comment by az** [comment]
@jprzybylski4 buttons look OK :)

i am always testing emails before dispatching them so no worry.

**Comment by az** [comment]
@jprzybylski4 i suggest different subjects - more straightforward.

**Comment by jprzybylski4** [comment]
ENG: E-commerce Berlin Expo - Important tips for your stand!
DE: E-commerce Berlin Expo - Wichtige Tipps zu eurem Stand!

**Comment by az** [comment]
@jprzybylski4 i will send it on thursday

**Comment by jprzybylski4** [comment]
Great, thank you for the confirmation
