### ISSUE TITLE
(IDEA) Create a new event for EBE 2023 already

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#125]
Plan minimum:
Create a new (offline) event so that we could already start preparing the booking map - to be switched on asap after May 5th. 
We will not use it on the day of the event but it will allow us to start sales for 2023 asap.

Plan maximum:
Create a new (offline for now event) so that we could prepare the booking map to be used during the Expo at the EBE sales point. The map wouldn't be visible anywhere on the public website - we'd still have EBE2022 map there. 
We'd just have a separate website (like https://ecommerceberlin.com/ebe23 or sth) that we could show on the TV at the EBE sales point and people would be able to book a specific stand already.

**Comment by az** [comment]
@jprzybylski4 i will set up a new event, clone map, ticket groups and tickets .... thats what i am capable of doing in a foreseeable future
