### ISSUE TITLE
VIP registrations - questions

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#126]
For the sake of clarity - questions in Polish:

- Jak nazywa się pole,w którym uzupełniany jest kod VIP i jak powinno być uzupełnione w linku? Wiem, że mozna wysyłać linki, które same uzupełniają kod VIP, ale nie wiem jak to zrobić.
- Czy w rejestacji VIP możemy dowolnie operować linkami / kodami, które będą autouzupełniane poprzez wysyłanie specjalnie generowanych linków?
- W jaki sposób exhibitorzy będą mogli zapraszać vip? Czy tylko przez stronę /vip?
- W jaki sposób możemy weryfikować, że konkretna osoba (VIP) - został zaproszony z indywidualnego zaproszenia firmy? Czy jeżeli będziemy korzystali ze strony /vip możemy stworzyć indywidualne kody (oparte np. o cname), które będą pozwalały nam na eksport tych danych z admina?

**Comment by az** [comment]
(and honestly i havent understood any single line)
