### ISSUE TITLE
(EMAIL) Exhibitors - additional services + electricity

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#127]
Please schedule and send the attached emails.

ENG: E-commerce Berlin Expo - do you need more electricity for your stand?
DE: E-commerce Berlin Expo - ist der Stromanschluss für euren Stand ausreichend?

[ebe6-additional-services-3-electricity.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8080677/ebe6-additional-services-3-electricity.zip)

**Comment by az** [comment]
@jprzybylski4 i can send it next week earliest... i will confirm on monday the exact day

**Comment by peterecommberlin** [comment]
@az  if so then we need to change the copy!

**Comment by az** [comment]
@peterecommberlin OK, i will try to send it tomorrow then

**Comment by az** [comment]
just for the record ... current status 

![Image 2022-02-24 12-51-33](https://user-images.githubusercontent.com/2198/155519190-6858f38c-395a-4a47-b3c5-7c5e57c2b781.jpg)

**Comment by az** [comment]
changed "power output" to power supply" @jprzybylski4 

dispatched
