### ISSUE TITLE
(BUG) More than one booth shown on company's public profile

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#128]
expected result
Only one, actual (A4.3) booth should be shown on the Anexia's profile

actual result
There are more than one booths shown

steps to reproduce
https://ecommerceberlin.com/exhibitors/anexia-itcom - scroll down to the booth location and map

proof
![image](https://user-images.githubusercontent.com/75311923/154537114-4d55bc59-653c-4788-9dfd-73140351c20b.png)

Severity/Priority
Minor (often)

number of users already affected (reporting this issue) of total users
1

team members who tested (apart from creator of bug report)
DK

**Comment by az** [comment]
@jprzybylski4 i believe the excessive markings are past (cancelled) purchases ?

**Comment by jprzybylski4** [comment]
Actually - cancelled booths are not shown on the list. 
Those are the booths from past editions: 
- B2.6 - EBE5
- B1.1 - EBE4
- B1 - EBE3

**Comment by az** [comment]
@jprzybylski4 thx. i am investigating it now...
