### ISSUE TITLE
TRANSLATION recent bookings list

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#133]
i have updated some base libs so this should be translated 

(if you do not want such feature - please make an issue - i will make it on/off)

![E-commerce Berlin Expo | Berlin | May, 2022 2022-03-01 23-55-57](https://user-images.githubusercontent.com/2198/156262856-52658f97-4525-409a-bb3b-30a4040f3692.jpg)

**Comment by jprzybylski4** [comment]
Before I decide I have a couple of questions:
- is there any chance to edit the way the companies are shown on the list? If it is we'd rather have fewer companies (let's say 5-10) but e.g. shown as a bulleted list.
- in the EBE case, could we place this list above the booking map instead? I don't think too many people will see it if it's at the bottom

**Comment by jprzybylski4** [comment]
agreed - thank you for the confirmation. It would be great if we could turn it on in May once we begin '23 sales

**Comment by az** [comment]
translated.
