### ISSUE TITLE
Enable the agenda widget on the website

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#134]
Time of the presentation + venue already assigned

**Comment by jprzybylski4** [comment]
FYI - We've checked and it seems that the widget is more or less working fine.
When you have a second could you just please tell me why the speaking slots at 16:00 are not visible on the agenda?
They've been added in admin. 
![filtered?tags=speaker 2022-03-14 15-51-11](https://user-images.githubusercontent.com/75311923/158197687-123dcae1-2c23-4e7c-914a-1656094e735a.png)

**Comment by jprzybylski4** [comment]
One more thing - and I do know it used to work the same way as now last time and during the EBV.
In the cases of two speakers presenting together: is there any chance we can show both names after clicking on the "info" button?
So far both speakers are shown on the agenda, but only one in the details:
![E-commerce Berlin Expo | Berlin | May, 2022 2022-03-16 14-08-04](https://user-images.githubusercontent.com/75311923/158596881-0118240e-940c-471a-b5b3-8e7a0f98bb19.png)
![E-commerce Berlin Expo | Berlin | May, 2022 2022-03-16 14-09-26](https://user-images.githubusercontent.com/75311923/158597001-742d2d68-e2fe-44ec-9235-52c009fcee87.png)

**Comment by az** [comment]
@jprzybylski4 plz create separate GH issue - it will be processed not earlier than in May.
