### ISSUE TITLE
(EMAIL) Exhibitors - fraudulent lists offers

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#136]
Please schedule and send the attached emails.

ENG: Warning: Fraudulent offers of E-commerce Berlin Expo participants list
DE: Warnung: Betrügerisches Angebot der E-commerce Berlin Expo Teilnehmerliste

[ebe-6-fraudulent-lists.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8179391/ebe-6-fraudulent-lists.zip)

**Comment by az** [comment]
@jprzybylski4  i suggest sending it via admin panel as it does not concern AM - assignment (honestly i dont have time to handle such kind of journalistic communication)

**Comment by jprzybylski4** [comment]
Sent via admin
