### ISSUE TITLE
(EMAIL) Exhibitors - company representatives #1

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#137]
Please schedule and send the attached emails.

ENG: E-commerce Berlin Expo - Time to register company representatives!
DE: E-commerce Berlin Expo - Zeit die Vertreter zu registrieren!

[ebe6-company-representatives.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8199387/ebe6-company-representatives.zip)

**Comment by az** [comment]
@jprzybylski4 please assign missing AM

**Comment by az** [comment]
![E-commerce Berlin Expo | Berlin | May, 2022 2022-03-15 11-31-51](https://user-images.githubusercontent.com/2198/158358842-ddcbed86-dc00-4e41-a2cf-1419dae1bbd3.jpg)

**Comment by az** [comment]
sent
