### ISSUE TITLE
(IDEA) Show both speakers in the details of the speaking slot

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#141]
**description**
So far we have both speakers shown on the agenda but only one in the "info"/details. It would be great if we could standardize it.

![158596881-0118240e-940c-471a-b5b3-8e7a0f98bb19](https://user-images.githubusercontent.com/75311923/158606916-84b966d2-b003-4e26-b42d-6e62a86191b0.png)
![158597001-742d2d68-e2fe-44ec-9235-52c009fcee87](https://user-images.githubusercontent.com/75311923/158606933-b6b70646-2ed1-4abf-8606-1fdaaad824b6.png)

**reason**
We have more companies willing to take a partner/customer with them to present together. It is a great opportunity for us (more practical knowledge + more recognizable brads to show) it would be great if we could show it. 

**list of benefits**
It is a great opportunity for us - more practical knowledge + more recognizable brands to show. It would be great if we could show it. 

**priority**
6

**team members who discussed the idea**
MT & JP

**Comment by az** [comment]
good news @jprzybylski4 

agenda widget has been totally rewritten (final version is visible on teh website)

![21  Targi eHandlu - Warszawa - 14 kwietnia 2022 2022-03-23 12-51-55](https://user-images.githubusercontent.com/2198/159693119-91150b53-5c12-4373-8a7f-4bb256f24665.jpg)

but i cannot tell the exact date when the updated library will be pushed to ebe website (there are some major differences that must me hidden first...like "recent bookings")

**Comment by az** [comment]
@jprzybylski4 live on ebe
