### ISSUE TITLE
Translations needed (refreshed schedule widget, refreshed company profiles)

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#142]
![Allegro pl invites you to a meeting at the E-commerce Berlin Expo 2022-03-23 15-39-57](https://user-images.githubusercontent.com/2198/159725156-68465962-0427-417f-a46f-ad6c956c5a85.jpg)

![Allegro pl invites you to a meeting at the E-commerce Berlin Expo 2022-03-23 15-36-43](https://user-images.githubusercontent.com/2198/159724484-4e5a9f39-1f38-4528-9994-af167b3c4ebe.jpg)
![Allegro pl invites you to a meeting at the E-commerce Berlin Expo 2022-03-23 15-37-00](https://user-images.githubusercontent.com/2198/159724560-2ce0d657-e208-4bfd-a0c8-dd3720be5ee5.jpg)

**Comment by jprzybylski4** [comment]
Translated
