### ISSUE TITLE
prepare domain, proxy redirector for sms campaign

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#146]

**Comment by az** [comment]
@marek-berlin UTM's ? (urgent) cc @jprzybylski4

**Comment by marek-berlin** [comment]
https://ecommerceberlin.com/visit?utm_source=visitors&utm_medium=sms&utm_campaign=agenda_ticket

**Comment by az** [comment]
@marek-berlin https://r.ecommberlin.com/__hash/code__ so replace (in your spreadsheet) what you have before  "ticket code" with "https://r.ecommberlin.com/"  

for instance find & replace - "tickets/" -> "https://r.ecommberlin.com/"

(working example https://r.ecommberlin.com/eazdvm )
