### ISSUE TITLE
Confirm badge templates for std and vip guests 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#148]
[ebe5_ticketdownload_vip.pdf](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8514485/ebe5_ticketdownload_vip.pdf)
[ebe5_ticketdownload.pdf](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8514486/ebe5_ticketdownload.pdf)

**Comment by jprzybylski4** [comment]
@az logotypes
https://drive.google.com/drive/folders/1YIvpF3xHgtbo6PYydoZeoaP3My-uNbcl

**Comment by jprzybylski4** [comment]
Regular ticket:
Change E-commerce Berlin Expo - to the official "full" logotype
Logotype tittle: Expo partner 
Logotype - https://github.com/ecommerceberlin/ecommerceberlin.com/issues/145
Date - 5th May 2022 10:00 - 17:00
Fees for short-term parking 
Hourly: EUR 2.00/hour
Daily pass: EUR 20.00

bottom sentence:
We advise you to use public transport as there is only a limited number of parking spaces available.

**Comment by jprzybylski4** [comment]
VIP ticket:
Change E-commerce Berlin Expo - to the short version of the logotype 
Enlarge "VIP"
Logotype tittle: Expo partner
Logotype - https://github.com/ecommerceberlin/ecommerceberlin.com/issues/145
Date - 5th May 2022 10:00 - 17:00

Above the parking details:
As a VIP visitor, you have priority access on the right side of the entrance. The Premium Badge allows you to enter the VIP Zone in hall 3 (next to the Stage A), which is inaccessible to regular visitors.

You can enter the garage via Schönenberg Strasse.
Fees for short-term parking
Hourly: EUR 2.00/hour
Daily pass: EUR 20.00
We advise you to use public transport as there is only a limited number of parking spaces available.

**Comment by az** [comment]
updated. live.
