### ISSUE TITLE
Check badge rep generator $90$

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#149]

**Comment by az** [comment]
@jprzybylski4 after huge research thats the only file i have come across https://res.cloudinary.com/eventjuicer/image/upload/v1580778201/ecommerceberlin_badge_template.pdf

**Comment by az** [comment]
@jprzybylski4 result is https://pages.ecommerceberlin.com/data/event_90/exhibitor_identifiers_202204191955.pdf

**Comment by jprzybylski4** [comment]
Is there any chance we could change this:
![badge_template pdf 2022-04-19 21-50-08](https://user-images.githubusercontent.com/75311923/164084301-0209738a-38a4-4c82-93ae-f6d3c058343f.png)

To our full official logotype?

**Comment by az** [comment]
@jprzybylski4 ofcourse 
> "wrzucilem znaleziona templatkę pod tickety non-visitor… trzeba nad nia posiedziec"
that was what i meant :D

**Comment by az** [comment]
@jprzybylski4 IMPORTANT

old generator (nonVisitor -> reps, spkrs, organizator) uses cname2 field which is absent in new exh registrations (cname2 is now company name ) ... i have a script to clone company names to exh registrations / cname2 but to make it work all company names must be set

https://staff.ecommerceberlin.com/ - i see some companies (approx 2) that have missing company names

also triple check if booth ids are copied to ticket's booth field as this is the second "bridge" to force old PDF generator to work

**Comment by jprzybylski4** [comment]
Cnames fixed - I just cannot fix Bigcommerce as their booking was already problematic in the past (most likely done through /premium instead of the map). However, they registered reps via other exhibitor profile that has the name set. 

Re booth ids - do you need those checked now or is it enough if I ask AM to do it tomorrow, before we export the badges?

**Comment by az** [comment]
@jprzybylski4 i advise to check it out before generating badges (generally it looks fine but there are often problems when exhibitors are changing locations, etc.)

anyway my work here is done - tutorial  https://github.com/ecommerceberlin/ecommerceberlin.com/issues/150 -
