### ISSUE TITLE
translate ticket download page

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#154]
![E-commerce Berlin Expo | Berlin | May, 2022 2022-04-21 12-49-16](https://user-images.githubusercontent.com/2198/164442699-dc1b0b77-e351-4300-b15c-da1ab0d6118f.jpg)

@jprzybylski4 if you checked that page - why you have not made it translated? :)

**Comment by jprzybylski4** [comment]
translated
