### ISSUE TITLE
(EMAIL) Exhibitors - Parking and logistics $45$

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#159]
Please schedule and send the attached emails. If possible (I know it's outside the agreed timeframe) please send it on Tuesday, April 26th.

ENG: E-commerce Berlin Expo - organisational information
DE: E-commerce Berlin Expo - organisatorische Infos

[ebe6-parking-and-logistics.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8546681/ebe6-parking-and-logistics.zip)

**Comment by az** [comment]
sent
