### ISSUE TITLE
EGA banner change

### ISSUE THREAD

**Issue by peterecommberlin** [ecommerceberlin/ecommerceberlin.com#16]
Grzecznościowo dodaję.

proszę podmienić baner EGA "vote for us" na EBV

Zestaw grafik dostępny pod linkiem: https://drive.google.com/drive/folders/1ndluC0TkW3bj-JhRLsf5HpECySm0Jr_Q

**Comment by az** [comment]
d010d37728a9e1485a67d91ea85eb83932dee40f
