### ISSUE TITLE
(EMAIL) Exhibitors - badge scanner

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#160]
Related to: https://github.com/ecommerceberlin/ecommerceberlin.com/issues/89

Please schedule and send the attached emails. If possible (I know it's outside the agreed timeframe) please send it on Thursday, April 28th.

[ebe6-scanner-app.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8542883/ebe6-scanner-app.zip)

**Comment by jprzybylski4** [comment]
Just one question - as I wasn't sure which manual is correct: nextgen expojuicer or this one https://raw.githubusercontent.com/eventjuicer/services/master/resources/views/emails/company/teh20-scanner-pl.blade.php

Should it work like that:

> Otwórz przeglądarkę na swoim smartfonie. Wejdź na stronę https://expojuicer.com i wybierz z listy nazwę swojej firmy. Po pojawieniu się komunikatu 'Ready!' możesz zamknąć przeglądarkę i od tego momentu skanować identyfikatory odwiedzających!
> Zeskanuj kod QR na identyfikatorze przy pomocy aparatu smartfona. Po zeskanowaniu pojawi się sugestia uruchomienia adresu URL - uruchom go. Każde kolejne skanowanie to użycie aparatu i uruchamianie adresu URL zakodowanego w kodzie QR. Dodawanie komentarzy jest opcjonalne.

or
> Skanujemy kod QR na identyfikatorze przy pomocy aparatu smartfona. Po zeskanowaniu pojawi się sugestia uruchomienia adresu URL - należy go uruchomić. Przy pierwszym skanie będzie trzeba wybrać nazwę swojej firmy. Każde kolejne skanowanie to użycie aparatu i uruchamianie adresu URL zakodowanego w kodzie QR. Dodawanie komentarzy jest opcjonalne.

I can always change it in the files

**Comment by jprzybylski4** [comment]
Forgot to add topics before:
EN: E-commerce Berlin Expo 2022 - How to scan the leads?
DE: E-commerce Berlin Expo 2022 - Wie scanne ich die Leads?

**Comment by az** [comment]
sent
