### ISSUE TITLE
(EMAIL) Visitors - register

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#161]
Copies available: https://docs.google.com/document/d/1CQN5yVkrJAUi-GaO0vABXpMQCGn7CIH80v7BGR_yqBg/edit#

It would be great if those could be sent on Thursday. 

Please let me know if you need PHP files.

**Comment by az** [comment]
@jprzybylski4 please provide txt or md files

**Comment by az** [comment]
![Slack | mark | fp20 | 63 new items 2022-04-26 15-47-27](https://user-images.githubusercontent.com/2198/165314486-280fcfa7-260d-4460-97be-f8234174b551.png)

**Comment by az** [comment]
@jprzybylski4 any change to have this PLAIN/RAW txt or md before EOD?

**Comment by jprzybylski4** [comment]
Mark is working on it - definitely will have it for you by EOD

**Comment by az** [comment]
@jprzybylski4 OK ... just to be understood clearly..... plain .txt, .md files with reference to images (cloudinary) is all i need.... i dont need anybody to sit on blade.php files now :)

**Comment by jprzybylski4** [comment]
[mail1.txt](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8571383/mail1.txt)
[mail2.txt](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8571384/mail2.txt)

**Comment by jprzybylski4** [comment]
The links are already added in the files, but just to be safe:

COVER PHOTO: https://res.cloudinary.com/ecommerceberlin/image/upload/v1646742196/EB_2022_master_files_540x300.jpg
SELECTED SPEAKERS
https://res.cloudinary.com/ecommerceberlin/image/upload/v1647954404/Newsletters/1.png
OR
https://res.cloudinary.com/ecommerceberlin/image/upload/v1647954404/Newsletters/2.png
MAIN SPONSORS
https://res.cloudinary.com/ecommerceberlin/image/upload/v1650631090/Newsletters/main_expo_partners3.png
TRACKING URL https://ecommerceberlin.com/visit?utm_source=visitors_alternative&utm_medium=email&utm_campaign=visitors_alternative_email

**Comment by az** [comment]
@jprzybylski4 thx

**Comment by az** [comment]
@jprzybylski4 sender - LZ?

**Comment by az** [comment]
because {{$footer}} only works with exh / companies

**Comment by az** [comment]
subjects taken from files

Be part of the biggest Berlin event dedicated to e-commerce only!

**Comment by az** [comment]
this is perfect case @jprzybylski4 why you should be coordinating ALL materials or spend some time to "educate" 

files were created in some "civil" editor - contains tens of markings that are human- / print- but for sure not from IT-world (like replaced quotes, or strange blank space, new lines)

contains markup that is not recognizable in visitor-related context  (thats why i asked to have plain data ...)  etc

**Comment by jprzybylski4** [comment]
Yes - sender LZ
Sorry about the files then, but I didn't have time to prepare them myself

**Comment by az** [comment]
28 567 emails scheduled to be sent...

**Comment by jprzybylski4** [comment]
Just FYI - if you scheduled any more emails to be sent or any follow ups please don't send them, as the outcome was mostly negative.
