### ISSUE TITLE
(EMAIL) Visitors - download the ticket

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#163]
A suggested copy of the email is attached. 
It would be great if we could send it today. 

[download_ticket_RSVP.txt](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8581535/download_ticket_RSVP.txt)

**Comment by jprzybylski4** [comment]
@az when could we have this email sent?

**Comment by az** [comment]
@jprzybylski4 no ETA at the moment. have some queue to process. (asking questions only slow down things...)

**Comment by jprzybylski4** [comment]
In this case @marek-berlin will send one more email from N2G now. We'd like to give them as much time to download as possible today

**Comment by az** [comment]
@jprzybylski4 feel free. at this edition i am not coordinating anything... just waiting for clear instructions and "frozen" strategy..... sending after 4pm seems pointless . shall i send it tomorrow ?

**Comment by jprzybylski4** [comment]
Ok, thanks for the confirmation. Could you please schedule the emails to be sent tomorrow and then a follow-up on Monday?

**Comment by az** [comment]
@jprzybylski4 yep

**Comment by az** [comment]
checked stats ...ca. 3000 going seems very OK as for the "age of the visitors database"

**Comment by az** [comment]
@jprzybylski4 download_ticket_RSVP.txt - this file is total SHIT.... not created in code editor...with mixed up markup, quotes etc.  (next issues with such files will be marked as invalid and closed.)

i am sending default message (updated) as it is more straightforward - more CTA-like

**Comment by az** [comment]
@jprzybylski4 reference files if you want to update them before Mon 

https://raw.githubusercontent.com/eventjuicer/services/958fd3fde94b0d1ccff52dd1e2706af461761dfb/resources/views/emails/visitor/ebe6-ticket-reminder.blade.php

txt version (for non html clients)

https://raw.githubusercontent.com/eventjuicer/services/958fd3fde94b0d1ccff52dd1e2706af461761dfb/resources/views/emails/visitor/ebe6-ticket-reminder_text.blade.php

**Comment by az** [comment]
@jprzybylski4 "then a follow-up on Monday" .... can you re-confirm this? as i can see @marek-berlin sent such reminder.

**Comment by jprzybylski4** [comment]
Mark is mostly sending logistics details now. I confirm - please send the emails
