### ISSUE TITLE
(IDEA) Add ticket download link in the registration confirmation as soon as we start sending tickets

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#168]
**description** 
Once we start sending the tickets to the visitors we could start adding the link to the ticket download in the confirmation email. 
Obviously if it's possible to add snippet [[token]] in the email.

**reason**
It would most likely have a positive effect on the ticket downloads in the last days before the Expo. 
Also, we usually assume that people who register closer to the event are more likely to come to the event so it would be great to keep them hyped about the event once they register. 

**list of benefits / areas that will benefit from the change**
Faster ticket download process. Bigger chance for the visitors to download the ticket and actually attend the event. 

**priority 1-10**
8

**team members (initials) who discussed the idea**
PSZ, MT

**Comment by az** [comment]
standard procedure since 2018.

**Comment by az** [comment]
re https://github.com/ecommerceberlin/ecommerceberlin.com/issues/169
