### ISSUE TITLE
Change the email confirmation - check the date

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#17]
At the moment the confirmation is confusing - it has the old date. 
Please change the event date in the confirmation to 24th February 2022

**Comment by az** [comment]
Przychodzi “We will meet on 27th of May at STATION Berlin, Luckenwalder Str. 4-6”
prosba o zmiane na:
 Thank you for your registration for E-commerce Berlin Expo 2022!
We will meet on 24th of February at STATION Berlin, Luckenwalder Str. 4-6
If you have any questions please do not hesitate to contact us visitors@ecommerceberlin.com
Du hast dich erfolgreich für die E-commerce Berlin Expo 2022 registriert. Wir sehen uns den 24.02.2022 in der STATION Berlin in der Luckenwalder Str. 4-6.
Falls Rückfragen bestehen, dann zögere nicht uns zu fragen unter: visitors@ecommerceberlin.com
regards! Lieben Gruß! E-commerce Berlin Expo Team
