### ISSUE TITLE
provide files of scanned visitors from ebe6

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#172]
its safe to put them here - i need plain files (.csv, .txt)

**Comment by jprzybylski4** [comment]
EBE6_scanned_visitors.csv

**Comment by az** [comment]
@jprzybylski4 no actual file - please re-upload

**Comment by jprzybylski4** [comment]
[EBE6_scanned_visitors.csv](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8651356/EBE6_scanned_visitors.csv)

**Comment by az** [comment]
@jprzybylski4 thx...it will take some time to write parser for this as it will be made from scratch
