### ISSUE TITLE
(EMAIL) Exhibitors - post event survey $30$

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#173]
Please schedule and send the attached emails.

Subjects:
ENG: E-commerce Berlin Expo 2022 - we’d love to hear your feedback!
DE: E-commerce Berlin Expo 2022 - wir warten auf euer Feedback!

[ebe6-survey.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8653531/ebe6-survey.zip)

**Comment by az** [comment]
sent
