### ISSUE TITLE
provide (EMAIL) to send photos download links 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#178]
example - https://raw.githubusercontent.com/eventjuicer/services/master/resources/views/emails/company/teh21-teh22-intro-pl.blade.php

@jprzybylski4 i can send it on monday 
OR you can send whatever you want whenevery you want as i have given you the URL to zip photos 

 https://photos.ecommerceberlin.com/[[company_id]]/ebe6

event old admin is enough

**Comment by jprzybylski4** [comment]
Also, the email already points out to the sales starting on Thursday, May 19th. If for any reason you cannot process everything in time please let me know and I will change the email copy.

**Comment by az** [comment]
sent (3 registrations excluded)
