### ISSUE TITLE
ecom v2 - translations needed

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#180]

**Comment by az** [comment]
@jprzybylski4 test page - https://ecommerceberlin.com/bmaptest (booths t1, t2, t2)

**Comment by az** [comment]
![E-commerce Berlin Expo | Berlin | February, 2023 2022-05-13 13-24-45](https://user-images.githubusercontent.com/2198/168273933-221c5e7c-ac17-42b4-a872-e3171dc2278b.png)

**Comment by az** [comment]
![E-commerce Berlin Expo | Berlin | February, 2023 2022-05-13 13-32-45](https://user-images.githubusercontent.com/2198/168274866-b8e67682-b187-49d7-81d2-999d62aed678.png)

**Comment by az** [comment]
![E-commerce Berlin Expo | Berlin | February, 2023 2022-05-13 13-33-21](https://user-images.githubusercontent.com/2198/168274919-cb8b18d8-3907-4961-a279-9a470bb9680a.png)

**Comment by peterecommberlin** [comment]
done
