### ISSUE TITLE
ecom v2 - create email confirmation template

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#181]

**Comment by az** [comment]
![Edit Template | SparkPost 2022-05-16 20-45-03](https://user-images.githubusercontent.com/2198/168661145-b9e9180e-5863-4166-94cb-2330385b4560.png)

@jprzybylski4

DE version? 
who should be @ footer / sender ?
which sender email hello@....  or you have some dedicated?

**Comment by jprzybylski4** [comment]
Please let me know if it needs any adjustments

Footer (for now): EBE team
sender: hello@

[ebe7-confirmation-email.txt](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8702617/ebe7-confirmation-email.txt)

**Comment by az** [comment]
@jprzybylski4 thx. should be ok.
