### ISSUE TITLE
(EMAIL) Exhibitors - sales timeline

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#184]
Subjects:
ENG: E-commerce Berlin Expo - Early Bird sales announcement
DE: E-commerce Berlin Expo - Early-Bird-Sales Ankündigung
[ebe7-sales-timeline.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/8702543/ebe7-sales-timeline.zip)

**Comment by jprzybylski4** [comment]
Please let me know if there are any adjustments to be done

**Comment by az** [comment]
"en" looks really fine @jprzybylski4 

im very curious about a reception and final output :)
