### ISSUE TITLE
TRANSLATION

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#187]
![E-commerce Berlin Expo | Berlin | February, 2023 🔊 2022-05-16 22-50-12](https://user-images.githubusercontent.com/2198/168680358-e816dd1b-062a-4241-af43-b65f2c5df0dc.png)

@jprzybylski4 i have added separate labels to reflect some more specific info (like booking till EOD and that it is for top30 of exh contest)

**Comment by az** [comment]
@jprzybylski4 second label is of course ... *.top30_description

**Comment by jprzybylski4** [comment]
translated - though it doesn't load on the page

**Comment by az** [comment]
thx.... i can see it locally so its ok (cache for sure)
