### ISSUE TITLE
(TRANSLATION) validate translations for transaction

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#189]
![E-commerce Berlin Expo | Berlin | February, 2023 🔊 2022-05-17 00-49-49](https://user-images.githubusercontent.com/2198/168694856-850142f8-3208-4b99-8007-fd71ebb25a39.png)

@jprzybylski4 for exhibitor.form.success i have used the copy from email confirmation (change if you want) , empty cart needs DE translation

**Comment by jprzybylski4** [comment]
German translation added.
Success message is ok
