### ISSUE TITLE
clone previous media, community, communication partner(s)

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#192]
![E-commerce Berlin Expo | Berlin | February, 2023 2022-05-19 11-10-35](https://user-images.githubusercontent.com/2198/169257875-522a2675-3837-4753-9933-8f8c7a22955c.png)

**Comment by jprzybylski4** [comment]
@az is there any chance you can copy the widget from previous edition as whole? 
If not I will ask Johnny to fill it in tomorrow.

**Comment by az** [comment]
that is the meaning of this self-assigned ticket, isnt it?
-- 
Regards / Pozdrawiam,

Adam Zygadlewicz

mobile: +48 605 501 601
skype: adam.zygadlewicz
http://fb.me/adam.zygadlewicz
http://twitter.com/az

**Comment by az** [comment]
cloned
