### ISSUE TITLE
Add company address to the registration form

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#193]
I'm not sure if it should be labeled as (IDEA) - please let me know if I should edit the issue. 

We'd appreciate it if you could add the company_address field to the registration form. It will make the agreement and proforma invoice creation much easier for the AMs. 

Currently these are the fields we ask for:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/75311923/169862272-2ed9773c-05f3-46c8-bac4-0b36791845f6.png">

**Comment by az** [comment]
resolved via 4e789af30efafa64a86738a14409c33977085d4a
