### ISSUE TITLE
TRANSLATE company_address

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#194]
![E-commerce Berlin Expo | Berlin | February, 2023 2022-05-23 23-52-52](https://user-images.githubusercontent.com/2198/169911638-aa04ec17-cda6-49be-a55e-f1ef761f544b.jpg)

**Comment by az** [comment]
re https://github.com/ecommerceberlin/ecommerceberlin.com/issues/193

**Comment by jprzybylski4** [comment]
done
