### ISSUE TITLE
update CFP timeline dates

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#195]

**Comment by marek-berlin** [comment]
September 1, 2022 - Submissions Open
October 3, 2022 - Internet Users’ public voting
October 19, 2022 - Public voting Nominees announcement
October 24, 2022 - Advisory Board voting
October 31, 2022 - Winners Announcement

**Comment by marek-berlin** [comment]
Fotki speakerów do podmianki: https://www.dropbox.com/sh/67yq4gxpvy70zqy/AABYjCCS1J_ImaZFcylhuLnLa?dl=0

**Comment by marek-berlin** [comment]
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271680/Speakers/2SH07600.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271688/Speakers/e-commerce-berlin-expo-2022-palej_pl-and-9028-2048px.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271688/Speakers/e-commerce-berlin-expo-2022-palej_pl-and-9239-2048px.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271687/Speakers/e-commerce-berlin-expo-2022-palej_pl-and-9043-2048px.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271689/Speakers/e-commerce-berlin-expo-2022-palej_pl-and-9411-2048px.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271690/Speakers/e-commerce-berlin-expo-2022-palej_pl-and-9637-2048px.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271691/Speakers/e-commerce-berlin-expo-2022-palej_pl-and-9634-2048px.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271689/Speakers/IMG_0832.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271689/Speakers/e-commerce-berlin-expo-2022-palej_pl-and-9549-2048px.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271689/Speakers/IMG_0594.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271690/Speakers/e-commerce-berlin-expo-2022-palej_pl-and-9582-2048px.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271691/Speakers/e-commerce-berlin-expo-2022-palej_pl-and-9634-2048px.jpg
https://res.cloudinary.com/ecommerceberlin/image/upload/v1661271689/Speakers/e-commerce-berlin-expo-2022-palej_pl-and-9400-2048px.jpg

**Comment by az** [comment]
re 57c1c8f3cd97162c909529f6d33b2d43af71b907
