### ISSUE TITLE
CFP banner / pop-up on the main page

### ISSUE THREAD

**Issue by marek-berlin** [ecommerceberlin/ecommerceberlin.com#198]
Adam, a czy myślisz, że jest szansa na jakiś banner albo pop-up (jak przy EGA voting), który mógłby nam podbić widoczność na stronie targów zgłoszeń do CFP?

W tej chwili mamy opcję "speaking" w burger menu, ale to jest tylko dla najbardziej cierpliwych poszukiwaczy :)

Wiadomo że cała wrześniowa promocja będzie w okół CFP, więc pytanie czy możemy to jakoś wzmocnić.

**Comment by az** [comment]
i believe EGN is more suited for this.
