### ISSUE TITLE
Adding some visual on the /speaking subpage

### ISSUE THREAD

**Issue by marek-berlin** [ecommerceberlin/ecommerceberlin.com#199]
Mam banery do CFP o całkiem przyzwoitej estetyce, które można by dać na stronie /speaking jako nagłówek. 

To zawsze była by większa spójność pomiędzy naszymi mailingami a stroną www.

Panuje opinia (inside&outside organizacji), że brakuje nam spójności pomiędzy materiałami promo. W mailingach i reklamach epatujemy żółtymi kolorami i potem ktoś wchodzi na stronę w zupełnie innym layoucie. 

Fajnie jakby był jakiś punkt zaczepienia, który dałby poczucie bezpieczeństwa że trafiliśmy w dobre miejsce :)

**Comment by az** [comment]
"Panuje opinia" killed it.
