### ISSUE TITLE
(EMAIL) Exhibitors - CFP 1st message info

### ISSUE THREAD

**Issue by peterecommberlin** [ecommerceberlin/ecommerceberlin.com#200]
SUBJECT:

EN: E-commerce Berlin Expo 2023 - submit your presentation proposal and become a speaker!
DE: EBE 2023 - Teile dein Präsentationsvorschlag mit uns und werde unser Speaker!

[ebe7-cfp-1st-message.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/9454983/ebe7-cfp-1st-message.zip)

**Comment by az** [comment]
sent
