### ISSUE TITLE
(MAINTENANCE) rozłączenie profili BB pack A2.1  i Printmate A2.2

### ISSUE THREAD

**Issue by peterecommberlin** [ecommerceberlin/ecommerceberlin.com#201]
Na ten moment wszystko jest podpięte pod BB Pack A2.1+A2.2 
Zmiany maila nic nie dają, edycja profilu również. Zawsze link prowadzi do publicznego profilu BB Pack. 
Prośba o przypisanie A2.2 do Printmate

**Comment by az** [comment]
1. @peterecommberlin new issues written not in english will be marked as invalid 
2. please confirm whether the request is still valid .... 

"Na ten moment wszystko jest podpięte pod BB Pack A2.1+A2.2" - WTF it means? *logotype is bbpack but the company name is printmate....  what is the real requirement for the company (i believe they have 2 separate brands)
