### ISSUE TITLE
update legal files

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#205]
source folder of markdown files is here https://github.com/ecommerceberlin/ecommerceberlin.com/tree/master/texts

**Comment by marek-berlin** [comment]
[registration_confirmation.html](https://github.com/ecommerceberlin/ecommerceberlin.com/blob/master/texts/registration_confirmation.html) this file seems to be outdated but after registration there is different (the right date) message

**Comment by az** [comment]
resolved via c917ebf79d297ea18c96fcaa8abc651de82d8ae9
