### ISSUE TITLE
CFP - provide updated opengraph template

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#206]
old template for reference 

![og_ebe2022_cfp](https://user-images.githubusercontent.com/2198/192507421-1ae854b1-bae0-4d30-b921-6ca7f74dd328.png)

**Comment by marek-berlin** [comment]
![Uploading vote-2023-template.png…]()

**Comment by marek-berlin** [comment]
here is also PSD in case it is needed: https://drive.google.com/file/d/16Qzf3lairDgZ2AiNK3Q0IEsdG8nFrOkK/view?usp=sharing

i can't upload it directly. github thing i guess

**Comment by az** [comment]
@marek-berlin 
(kindergarten part 10)
can u provide vector format (all fonts as curves) ? afair we used only open formats - SVG, PDF, etc and you should never accept such files from agencies

**Comment by marek-berlin** [comment]
i thought PSD will do the work. 

working on AI format

**Comment by az** [comment]
@marek-berlin can u ku..a read? :) open sourced -----> SVG, PDF
i am not using any proprietary software since 2015

**Comment by az** [comment]
such process should take max 5 minutes
1. repository with old vector files used as templates (SVG, PDF)
2. open in affinity...fix date
3. upload

**Comment by marek-berlin** [comment]
yep, we can do that in 5 minutes.

but in affinity, the original font with the date looks broken.

here it is:
![Uploading vote-2023-template-ok.svg…]()

we can send the perfect version at 5pm if you can wait. if not, it is what we have.

**Comment by marek-berlin** [comment]
this is the original version from photoshop. looks better

https://user-images.githubusercontent.com/37836678/192760075-9be18a0d-339f-45e2-ae44-c546d83f9579.png

**Comment by az** [comment]
> but in affinity, the original font with the date looks broken.

thats WHY we use vector files with text/fonts changed into curves  (vector) BY AUTHOR....this guarantees i have vector files (can upscale, downscale without quality loss) and do not have to think about fonts used .....

**Comment by marek-berlin** [comment]
updated PDF

[vote-2023-template3.pdf](https://github.com/ecommerceberlin/ecommerceberlin.com/files/9665002/vote-2023-template3.pdf)

**Comment by az** [comment]
@marek-berlin amazing! thanks :)
