### ISSUE TITLE
 zmianę linku do profilu Kaufland

### ISSUE THREAD

**Issue by peterecommberlin** [ecommerceberlin/ecommerceberlin.com#207]
kaufland prosi o zmianę linku do ich strony z 

https://ecommerceberlin.com/exhibitors/kaufland-ecommercecom 

na 

https://ecommerceberlin.com/exhibitors/kauflandglobalmarketplace

trują o to więc byłoby dobrze serio podmienić

**Comment by az** [comment]
1. english please!
2. they have @kaufland-ecommerce.com domain so the (automatically generated / not editable) slug is correct...
