### ISSUE TITLE
[CFP] Visibility of past-deadline submissions

### ISSUE THREAD

**Issue by EcommberlinFab** [ecommerceberlin/ecommerceberlin.com#214]
**How it is**: there are some submissions sent after 30.09 and they're not visible on the website.
**How we need it to be**: well, **visible**.

THX!
_If this is sth that I can do myself, just let me know ;)_

**Comment by az** [comment]
@EcommberlinFab i have relaxed some API requests limits (setting was 350) please confirm if everything is OK now

**Comment by EcommberlinFab** [comment]
@az and it is indeed. Thank you! ^^
