### ISSUE TITLE
(BUG) (CFP) LinkedIn profile post showing past EBE date

### ISSUE THREAD

**Issue by EcommberlinFab** [ecommerceberlin/ecommerceberlin.com#215]
LinkedIn profile post showing past EBE date.
Contestants using the LI promo feature are getting a post sayin that thing will take place in may.

Environment - n/a

Expected result:
Post showing actual date of upcoming EBE.

Actual result:
Post with old date.

Steps to reproduce
Simply using the feature.

**Proof:** [screenshot.](https://res.cloudinary.com/ecommerceberlin/image/upload/v1664880769/Call%20for%20Papers%202022/Zrzut_ekranu_2022-10-4_o_12.18.58.png)

Severity/Priority:
Major

Number of users already affected: 3

Team members who tested (seen in this case):
AS, AD

**Comment by az** [comment]
thank you for the report @EcommberlinFab 

after quick check i can say that translations are not updated (i believe it was omitted by @marek-berlin )

normally simple "may" or "2022" in search should do the trick to find all outdated translations so do it please (i will set up separate issue for this)

![ may 2022-10-04 13-05-39](https://user-images.githubusercontent.com/2198/193804014-1452076c-f025-42a9-9b4a-6c3867f66dad.jpg)
