### ISSUE TITLE
(MAINTENANCE) re-revise all translations and update it to 2023 edition 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#216]
re: https://github.com/ecommerceberlin/ecommerceberlin.com/issues/215

![ may 2022-10-04 13-05-39](https://user-images.githubusercontent.com/2198/193804180-67e3177a-d543-4f9d-ae1d-8e23e7563bbb.jpg)

**search for may, 2022 etc**

please let me know when finished and i will close this issue

**Comment by az** [comment]
@EcommberlinFab can we close it? done?

**Comment by EcommberlinFab** [comment]
Yup.
