### ISSUE TITLE
(MAINTENANCE)(CFP) Visibility of CFP votes

### ISSUE THREAD

**Issue by EcommberlinFab** [ecommerceberlin/ecommerceberlin.com#217]
Just got info that CFP votes should become visible for participants asap. Preferably tomorrow (12.10)... 
_Yeah, I know this date is ridiculous. Sorry for that again!_

Reason:
The voting is near its end.

Benefits:
The contestants will have some time to react and generate more clicks.

Team members (initials) who discussed the idea:
**MM**, AD, AS, FS

**Comment by az** [comment]
@EcommberlinFab - no problem. i will reveal it ASAP.

**Comment by az** [comment]
@EcommberlinFab revealed.
