### ISSUE TITLE
Big problem with our website - "analyticsy nie rozumieją urli - stron wejścia"

### ISSUE THREAD

**Issue by marek-berlin** [ecommerceberlin/ecommerceberlin.com#224]
Wybacz, ale to zgłoszenie będzie po polsku. Generalnie Analytics nie rozpoznaje od 2 miesięcy z jakiej strony są wejścia na naszej stronie. Ruch z ostatniej miesiąca i masz 

![Screenshot 2022-10-28 at 11 56 04](https://user-images.githubusercontent.com/37836678/198560180-0d654d1e-3a3c-4190-abde-f8d55e8c3b80.png)

To się dzieje w momencie gdy na stronie mieliśmy 20.000 visitorsów.

Jak sprawdzimy witrynę np. /visit to robi się jeszcze ciekawiej. Do sierpnia ruch się pokazywał i naglę go odcięło (pomimo 4x wzrostu ruchu na całej stronie). Tem sam scenariusz na każdej podstronie.

![Screenshot 2022-10-28 at 11 58 33](https://user-images.githubusercontent.com/37836678/198560705-6bc7bb11-c355-42c6-bf61-ac30b3248f78.png)

Czy może wprowadzaliśmy jakieś zmiany na stronie od sierpnia? Może mamy jakąś rozpiskę co było zmieniane? Wtedy będzie nam łatwiej znaleźć przyczynę dlaczego oba analyticsy nie rozumieją urli - stron wejścia a jeszcze parę miesięcy temu (not set) było rzadkością.

**Comment by az** [comment]
nie ma związku z moją pracą
