### ISSUE TITLE
URL tracking lost to subpages (call follow up)

### ISSUE THREAD

**Issue by marek-berlin** [ecommerceberlin/ecommerceberlin.com#229]
Mam zagadkę detektywistyczną. To jest powiązane z drugim zgłoszeniem o tym, że nie widać ruchu z podstron w Google Analytics.

Współpracujemy sobie z tą Agnelique z Internet World. Robią dla nas artykuły i newslettety w których nas promują: 

Przykładowy art:
https://www.gfm-nachrichten.de/news/wie-amazon-mit-ihrem-online-marktplatz-haendlern-zum-erfolg-verhilft/

W każdym arcie / newsleterze stosujemy taki link trackujący:
https://ecommerceberlin.com/visit?utm_source=gfm_article&utm_medium=gfm_article&utm_campaign=gfm_article_payments_link

Oni puszczają newsletter, który jest całkiem spory. 
![image (3)](https://user-images.githubusercontent.com/37836678/202848105-467a8abb-97e4-44b1-b1be-612c29aa8e3b.png)

**Jak się przyjrzysz to mamy tylko w tym mailingu 600 clicków w mailchim a Google Analytics w ogóle tego nie widzi.**
(dodam tylko że widziałem ten ich panel live a ta Pani nie jest tak technicznie zaawansowana, żeby mi fałszować na żywo te statystyki).

**Comment by marek-berlin** [comment]
Przejrzałam jeszcze raz oba analyticsy (UA i GA4), stworzyłam nawet testowy widok danych - żeby upewnić się, jak widziany jest ruch w obu widokach, i wygląda to tak, jakby oba narzędzia na raz odnotowały zwiększony ruch z directa.
Nie ma dodanych wykluczeń witryn odsyłających, które mogłyby "czyścić" źródło wejścia.

![image (4)](https://user-images.githubusercontent.com/37836678/202848265-36359244-f74c-4b15-b62c-7d8ca70a52d1.png)
![image (5)](https://user-images.githubusercontent.com/37836678/202848269-f9207f9c-b888-4f11-9df7-b3c285910d25.png)
![image (6)](https://user-images.githubusercontent.com/37836678/202848272-11c7c7ba-9a6a-4cc4-82c0-568e949caf05.png)
![image (7)](https://user-images.githubusercontent.com/37836678/202848273-c72baedf-6e96-437c-9597-a5c568db0efe.png)

Sprawa wygląda dziwnie - i przyznam, że pierwszy raz coś takiego widzę.

A mianowicie:

1. gdy się w wchodzi z linku z artykułu to UA w sekcji Czas rzeczywisty dobrze widzi źródło / medium wizyty i docelową stronę. To co odbiega od normy to ilość czasu jaką muszę odczekać by zobaczyć mój ruch - w witrynach nie zbudowanych na Java Scripcie własny ruch widać niemal natychmiast.

2. pomyślałam, że jeśli jest zatem zwiększona ilość wejść z directa, to może chociaż po stronie wejścia będzie można mniej więcej oszacować jak wzrosła ilość wejść na stronę od momentu emisji artykułów i newslettera - i tu zastałam właśnie coś niespotykanego: Analytics przypisał 99,47% wejść na stronę do strony (not set):
image.png
link do screenu: https://monosnap.com/direct/nPFO4b4ZO6vBe4CfFwMjHZ8sGDc8AA

Jeśli chciałabym zobaczyć ile było wejść na podstronę /visit to okazuje się, że tylko 5 w ciągu 2 m-cy a to niemożliwe wg mnie:
image.png

link do screenu: https://monosnap.com/direct/KQ2un3YkpPHTAE9Rjo8FZcYS5uTtYl

W artykułach znajduje się też taki link: https://ecommerceberlin.com/exhibit?utm_source=gfm_article&utm_medium=gfm_article&utm_campaign=gfm_article_payments_link
i jak chciałam sprawdzić w UA ilość wejść na tą podstronę, to w ciągu 2 mcy nie odnotowano ani jednego wejścia na taką podstronę:

image.png

link do screenu: https://monosnap.com/direct/SZbfM0NPSuiTgD3uF9ujQg8YlWiNtB

3. sprawdziłam jak to wygląda w GA4 - też jest masa (not set'ów), nie ma też utmów.
Jeden z artykułów widziałam, że ma utm press_relase i prowadzi do urla /speaking. Ga4 utm wyłapał w 4 sesjach, nie wyłapał na jaki url trafił użytkownik:

image.png

link do screenu: https://monosnap.com/direct/O8Go9t8PMqHNsdkcwQam2F5MMLXVji

4. konsultowałam z działem SEO skąd to może wynikać - po pierwsze należałoby sprawdzić co widać w Google Search Console - ostatnio wspominałam, że nie mamy do tego dostępu. Po drugie - w najbliższych dniach nasz kolega sprawdzi jeszcze jak Google radzi sobie z "rozumieniem" tej strony.

5. Zauważyłam spadek współczynnika odrzuceń - ten spadek następował od połowy sierpnia a obecnie jest nierealnie niski.
image.png
 link do screenu: https://monosnap.com/direct/Mysqf5hSnUVWUJSI9ZwfcOU3BCt8Hn

**6. Czy może wprowadzaliście jakieś zmiany na stronie od sierpnia? Może masz jakąś rozpiskę co było zmieniane? Wtedy będzie nam łatwiej znaleźć przyczynę dlaczego oba analyticsy nie rozumieją urli - stron wejścia a jeszcze parę miesięcy temu (not set) było rzadkością.**

**Comment by az** [comment]
nie ma związku z moją pracą
