### ISSUE TITLE
(BUG) NEW featured exhibitors are not visible on the website

### ISSUE THREAD

**Issue by peterecommberlin** [ecommerceberlin/ecommerceberlin.com#232]
In the featured exhibitors' section companies from the previous edition are still visible on the website. I marked NEW companies from ebe7 in expojucier (16 brands) and it worked for a second but after one website refresh everything got back to the previous version.  

Don't blame me but i'm not sure if i did it wrong or not... on ebe6 (expo juicer) i turned off companies that shouldn't be listed as featured. Have no idea how to deal with it...

**Comment by az** [comment]
![EventJuicer 2022-11-23 15-04-13](https://user-images.githubusercontent.com/2198/203567171-ed6c14b6-5386-45df-93b1-b5e19fcc6175.jpg)

@peterecommberlin all companies marked as featured are visible on the website

i cannot see any errors.......or unchecking companies does not work?

**Comment by peterecommberlin** [comment]
so why these are still visible? 

![Screenshot 2022-11-23 at 15 11 55](https://user-images.githubusercontent.com/35766428/203568256-76f05987-80e8-48c9-9839-53a61c602477.png)

**Comment by az** [comment]
@peterecommberlin i will investigate that...maybe some cache

**Comment by az** [comment]
@peterecommberlin 99% cache problem.....i will make fresh build
