### ISSUE TITLE
(EMAIL) EGA submissions - publishing: 01.12

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#234]
EGA MAIL BASED ON: 
https://github.com/eventjuicer/services/blob/master/resources/views/emails/company/ebe6-awards-reminder-en.blade.php
https://github.com/eventjuicer/services/blob/master/resources/views/emails/company/ebe6-awards-reminder-de.blade.php 

**CHANGES**

ENGLISH:
6th edition of the E-commerce Germany Awards
The deadline for submitting the entries is January 6th, 2023.

**and this section:**

Even getting on our shortlist of attendees could help you grow your brand awareness and promote your business to new clients. By entering you can also provide clarity on your objectives and ambitions while crucially comparing yourselves with competitors.

**should be changed to this one:**
Participation in E-commerce Germany Awards is a great opportunity to gain additional visibility in the industry, develop brand awareness among potential clients and competitors, motivate your teams and make your organization the destination for top talents!

GERMAN:
dass die 6. Ausgabe der E-Commerce Germany Awards gestartet ist!
Die Deadline für die Anmeldung ist der 6. Januar 2023.

**and this section:**
Selbst die Teilnahme kann eurem Unternehmen helfen, die Brand Awareness zu steigern und bei potenziellen Neukunden auf dem Radar aufzutauchen. Durch eure Teilnahme könnt ihr auch Klarheit über eure Ziele und Ambitionen schaffen und euch mit euren Mitbewerbern vergleichen.

**should be changed to this one:**
Die Teilnahme an den E-Commerce Germany Awards ist eine große Chance, die Bekanntheit in der Industrie und die Brand Awareness bei potenziellen Kunden und Konkurrenten zu steigern, Mitarbeiter zu motivieren und Euer Unternehmen zu einem Ziel für Top-Talente zu machen!

QUESTION: 
May we send the e-mails as different Account Managers like recently? As Dominik, Adem and Marianna, please?

**Comment by az** [comment]
@klaudia2209 i will dispatch it tomorrow (friday) before noon

**Comment by klaudia2209** [comment]
Ok.
