### ISSUE TITLE
(QUESTION) Masterclasses - questions - how can we add masterclasses' speakers to admin page? 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#235]
Hello, @az we have some questions. 

How can we add masterclasses' speakers to admin page? Can we make an upgrade of the exhibitors on our own? How does it work?

**Comment by az** [comment]
@klaudia2209 @peterecommberlin should help you with that...

generally
1) https://pages.ecommerceberlin.com/admin/booking
2) any past purchase + upgrade (button upgrade on purchase details page)
3) using front page https://ecommerceberlin.com/masterclasses

**Comment by klaudia2209** [comment]
@az ok, thank you, I know how it works now. 

I have another question - what's the role of the tickets? I see that they appear in 'orders' in the panel, but are there any other features appearing in the panel after upgrade?
