### ISSUE TITLE
(BUG) htttps://ecommerceberlin.de & norton - page is blocked, seems to be unsafe 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#237]
I receive an information from Lucas that when:

1) you **type** the website: ecommerceberlin.com or ecommercewarsaw.com
2) you refresh the main page or subpages 

these view appear: 
![image (1)](https://user-images.githubusercontent.com/118257251/204837871-826777f9-a630-41c8-9b95-6df0e4deddfd.png)
![image](https://user-images.githubusercontent.com/118257251/204837877-dbd6dc41-99c7-43ab-a847-265f78ff81a1.png)

Another thing is that Lucas has the name of the website marked in red in his mail box: 

![image (2)](https://user-images.githubusercontent.com/118257251/204838614-89b351b3-d02f-411a-a323-5f621323ffdc.png)

Lucas and the client have similar problem. The client is Teambank - we are waiting for the screenshot from them. 

It seems that Norton - antivirus - considers this page as unsafe. 

May we do anything about it?

**Comment by az** [comment]
@klaudia2209 i am not using NORTON (do we have 1990s? :) so ....

please submit desired URLs as we are receiving "false positive" here (we are 100% safe - otherwise the browser would mark our SSL protocol as unsafe)

here is the URL https://submit.norton.com/

(generally try to use google and find answers for issues concerning 3rd party software.....i am not working at NORTON :)

**Comment by klaudia2209** [comment]
Yeah, I was checking if our certificate is still valid and it was ok. 

I know that you don't work there, but you have an experience and you found the solution. It's also about sharing knowledge how to fix something. 

Thank you!

**Comment by az** [comment]
@klaudia2209 yes i have experience in pasting "why norton marks website unsafe" :>

the only test we should respect is testing SSL (as there are 200 versions)...if we have contemporary version and we are better than good.
![ssl labs](https://user-images.githubusercontent.com/2198/205014229-1ac737b8-c2db-4fb5-ac80-5b7cccaa076e.jpg)

**Comment by klaudia2209** [comment]
Haha, I met Norton yesterday, but I will know what to do next now :D 

wow, safety master! This looks reaally good :)
