### ISSUE TITLE
(QUESTION) Masterclasses flow

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#238]
what happens after sending submission to PARTICIPATE  in the workshops **AS PARTICIPANT?**

**Comment by az** [comment]
all submissions are visible in company account.ecommerceberlin.com panel .... in RSVP section (currently disabled)

organizer can click approve / reject 

a) approving 
* organizer gets all contact info
* participant gets info
* participant is being upgraded to VIP

b) rejecting
* participant gets info

**Comment by az** [comment]
> What if they resign from one of the slots in advance and let us know about it? Can the speaker accept someone else?

**Comment by az** [comment]
> For how many slots can they register? 2?

2 is "the setting" as it was @ TEH .... honestly i have not checked (YET) how many parallel participants were finally accepted
anyway..... i think it depends on the total number of masterclasses (2 seemed reasonable for 14 workshops...if having less i would consider 1.... ALSO i think it depends on when we want to start with participants applications..... 2 was OK because of the short time)

**Comment by az** [comment]
> > What if they resign from one of the slots in advance and let us know about it? Can the speaker accept someone else?

@klaudia2209 take a look at the FLOW at the beginning of this issue (thats the reason its good to have THREADS and do not duplicate)

organizer accepts / rejects so " if they resign from one of the slots in advance " is something not applicable...there is no way to implement that now...... we could if we decided 1 month before when we started to discuss it...now its too late... there is only a time to polish things

**Comment by klaudia2209** [comment]
ad.1a)Total number of masterclasses is 10. So probably 1 masterclass would be ok. 
ad. 1b) starting date of participants applications - probably after agenda publication, not before, so maybe in middle/ at the end of the January I suppose 

ad. 2. I see and I understand. What about extreeeme situations - e.g. 10 people resigned. Can we give the possibility to the speaker to accept other 10 people? Manually?

**Comment by az** [comment]
ad 1) i think its doable
ad 2) "10 people resigned" .... as i wrote "THEY CANNOT"... so you wanted to write "10 people wrote an email to use they cannot participate?" ....... well.... we can create 1000 different scenarios but does it really make sense? .... we can manually process some resignations.....we had no such situations (in mass scale) so i could think of some automated way.....

**Comment by klaudia2209** [comment]
1) ok 
2) ok

**Comment by klaudia2209** [comment]
@az 

I confirm that participant will choose 1 masterclass only. 

We changed the time slots a little bit - first masterclass will start at 10:20. We have 10 minutes of break between masterclasses. 

Probably we will release another slot of masterclasses to have 12 in total, but I don't know when it will be (I think that it's more Mark & Peter decision in this case). Mark said that we can add them manually later. On the masterclasses website there will be a view available for participants of masterclasses.

**Comment by az** [comment]
@klaudia2209 i have created another build of website to reflect new time slots - i hope it is final...every time you change timeslots (like 10:30->10:20 or add totally new time) schedule on the front page would have to be updated (website rebuilt)

re: 1 masterclass per participant  - i will work on that.

**Comment by klaudia2209** [comment]
Time slots are final, but if we add another two masterclasses - we will need to add one more slot. I prefer to let you know about it earlier.

re: sounds good.
