### ISSUE TITLE
(TRANSLATIONS) Provide masterclasses application form confirmation EMAIL translations

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#242]
![Edit Template | SparkPost 2022-12-05 11-23-36](https://user-images.githubusercontent.com/2198/205613789-d1fc2a83-9cf4-4fdf-ae12-fd044c418492.jpg)

sender - who is the BOSS of workshops-related communication?

subject - provide different if needed

CONTENT - polish example provided

**Comment by klaudia2209** [comment]
**ENGLISH VERSION OF THE E-MAIL ONLY**

TOPIC: 
Thank you for your application! | Masterclasses @ E-commerce Berlin Expo 

SENDER: 
E-commerce Berlin Expo team <masterclasses@ecommerceberlin.com>

Hello, 

Thank you for submitting your application to run masterclasses during E-commerce Berlin Expo 2023. We are glad that you would like to be a part of our knowledge center! 

Here is a short summary of provided information about your masterclass: 

First name and last name:
Company name:
Workshop title:

Best regards,

EBE Team

**Comment by az** [comment]
updated

**Comment by klaudia2209** [comment]
thank you
