### ISSUE TITLE
(TRANSLATION) - masterclasses (TARGET PARTICIPANT) application confirmed

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#243]
PL version as an example

`Cześć !
Organizator Warsztatu zaakceptował Twoje zgłoszenie.

Strefa w Hali 3, godzina
Prowadzący: z firmy

To nie koniec dobrych wiadomości! Masz dostęp do strefy VIP (Hala 3).

Do zobaczenia!
`

**Comment by klaudia2209** [comment]
`Hello, 

Thank you for your application. Masterclass’ host has already accepted your application.
Masterclass will be delivered in Hall 2, near the VIP zone powered by FedEx, at: hour
Speaker: company name

See you there!

EBE Team
_____

Hallo, 

Vielen Dank für deine Bewerbung. Der Masterclasses-Leiter hat deine Anmeldung angenommen.
Die Masterclasses werden in Halle 2, in der Nähe der VIP-Zone powered by FedEx, stattfinden: 
Sprecher: Firmenname

Wir sehen uns dann!

EBE Team
`
