### ISSUE TITLE
(TRANSLATION) - masterclasses (TARGET PARTICIPANT) application rejected

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#244]
polish version as an example

`Cześć !
Niestety organizator Warsztatu () nie zaakceptował Twojego zgłoszenia!

Spróbuj zapisać się na inny warsztat - https://targiehandlu.pl/workshops

Pamiętaj, że na Targach są 4 ogólnodostępne sceny prezentacyjne i 150 stoisk!

Mamy nadzieję, że do zobaczenia!

`

**Comment by klaudia2209** [comment]
EN i DE w 1 mailu: 

`Hello,

The Masterclass' speaker hasn’t accepted your application, unfortunately. Check if there are slots available in other masterclasses and try to secure yourself a seat.

If you don’t find any masterclasses - no worries. Take a look at the agenda of the 5 stages at the EXPO - there are a bunch of inspiring presentations!

We hope to see you there!

EBE team

______

Hallo, 

Der Masterclasses-Leiter hat deine Bewerbung leider nicht angenommen. Prüfe bitte, ob in anderen Masterclasses noch Plätze frei sind und versuche, dir einen Platz zu sichern.

Falls du keine Masterclasses findest - kein Problem. Dann werfe doch einen Blick auf die Agenda für die 5 Bühnen auf der EXPO - es gibt eine Menge inspirierender Präsentationen!

Wir sehen uns dort!

EBE Team
`
