### ISSUE TITLE
(MAINTENANCE) - Masterclasses for the participant page

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#246]
Hello, @az 

I have few questions regarding masterclasses' page: 

1. can we show the view for participants on the masterclasses page already? I will prepare the translations. 
2. can I get a link to teh workshops' website to compare it to our page? 

I remember about the translations of the e-mails.

**Comment by az** [comment]
@klaudia2209 how is it going with this? 

 what is the schedule of masterclasses? i can see 10:30, 11:45 and 13:00 ....i believe 10 organizers / 2 tracks means 5 slots .

**Comment by klaudia2209** [comment]
hello @az 

1) we had discussion yesterday about timeline and slots of masterclasses, we will work on it soon 
2) ok, secret URL will be helpful

**Comment by klaudia2209** [comment]
Missing presentation_time and presentation_venue added

**Comment by az** [comment]
@klaudia2209 i hope the timetable is now final otherwise i will have to make new build so that schedule at https://ecommerceberlin.com/masterclasses/temp?q= would work
