### ISSUE TITLE
(TRANSLATION) association partners widget title

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#249]
re: https://github.com/ecommerceberlin/ecommerceberlin.com/issues/248

![E-commerce Berlin Expo | Berlin | February, 2023 2022-12-14 12-32-22](https://user-images.githubusercontent.com/2198/207584372-dfe7c755-dfc9-4d3a-bc6d-e6e063958d3e.jpg)

**Comment by klaudia2209** [comment]
I added the translation, lowercase, I checked multiple times, it should be ok, but it doesn't appear on the website. Could you refresh it, please?

**Comment by az** [comment]
@klaudia2209 thanks for the info....closing this issue and of course forcing fresh build of the website

**Comment by klaudia2209** [comment]
thank you
