### ISSUE TITLE
(E-MAILS)(QUESTION) Dominik as a default sender 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#251]
Hello, 

regarding the sender of the e-mails - if we don't assign a proper AM in time, can we send the e-mails as Dominik instead of Marta?

**Comment by az** [comment]
@klaudia2209 checked that... it was set up but somehow MM wasnt unmarked so the system picked the user with smaller ID ... now this usecase should be resolved

**Comment by klaudia2209** [comment]
Perfect, thank you so much!
