### ISSUE TITLE
(QUESTIONS) - template with the companies' logo - redesign

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#252]
Hello, @az 

we want to prepare a new template for the companies to put their logo (EGA voting, promoninja). 

Questions: 

1) can we use the white space on the right/left? 
2) how big is the protective field for the logo?

<img width="966" alt="image" src="https://user-images.githubusercontent.com/118257251/207616144-b4114c79-ee0e-4c5b-9ca7-71d3c62b0708.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/118257251/207616481-fa0f41a4-b6ab-445b-8bc2-37cee062bf41.png">

**Comment by az** [comment]
@klaudia2209 we can change the template of course but we cannot add anything but the logotype dynamically (only 1 dynamic image is possible)

**Comment by klaudia2209** [comment]
@az ok, I understand, but can we make the white space for a logo smaller? E.g. can we use these red rectangles as a part of the template? Marketing team would like to make this template more attractive (not only yellow stripes on the top and on the bottom) 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/118257251/207626949-59ec32ce-7119-40e0-acfb-2f2925d34325.png">

**Comment by az** [comment]
@klaudia2209  example URL to final dynamically created image is 

https://res.cloudinary.com/eventjuicer/image/upload/c_fit,h_210,w_800/u_ebe5_template_en,y_10/v1546731988/c_1075_logotype.png

background image ("ebe5_template_en") is 960px wide
as you can see (from above URL) constraints for company logotype  (in above example "c_1075_logotype") are 800x210 so (960-800)/2 = 80px per side, right?

and

we cannot change it as (for the 5th time) this is SHARED code/SaaS.. changes would touch TEH etc

we can only change background image 

i'm afraid i do not have time to discuss it further...if you want to have bg image replaced (we have to) - please create fresh (MAINTENANCE) issue

**Comment by klaudia2209** [comment]
I understand, thank you. When we will have a new image, I will create a new issue.
