### ISSUE TITLE
(E-MAIL) visitor's e-mail, sent after registration for the event 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#253]
Hello @az,

we would like to change the content of the e-mail which is send to the visitors right after registration. We wanted to add some info about the free tickets to avoid questions from the visitors. 

**Please note that there is english and german version in the 1 e-mail.** 

**SUBJECT:** Thank you for registration | E-commerce Berlin Expo 2023

Hello, _name_!

Thank you for registering for E-commerce Berlin Expo 2023!
You will receive your free ticket via email a few days before the event.
Keep an eye out for email updates on the conference agenda, speakers, and exhibitors, or simply follow us on LinkedIn for tips on how to get the most out of EBE 2023!
If you have any questions please do not hesitate to contact us at [visitors@ecommerceberlin.com](mailto:visitors@ecommerceberlin.com).
Kind regards
E-commerce Berlin Expo Team

Du hast dich erfolgreich für die E-commerce Berlin Expo 2023 registriert.
Dein kostenloses Ticket erhältst du ein paar Tage vor dem Event per E-Mail.
Achte auf Neuigkeiten zum Konferenzprogramm, zu den Speakern und Ausstellern und verfolge uns auf LinkedIn, um Tipps zu holen, wie man den größten Nutzen aus der EBE 2023 ziehen kann!
Bei Rückfragen, zögere nicht uns unter [visitors@ecommerceberlin.com](mailto:visitors@ecommerceberlin.com) zu fragen.
Lieben Gruß!
E-commerce Berlin Expo Team

Current version: 
<img width="557" alt="image" src="https://user-images.githubusercontent.com/118257251/207818468-628e9cdb-c88d-4fb9-903e-cc0bdec6239c.png">

**Comment by az** [comment]
updated

**Comment by klaudia2209** [comment]
Awesome, thank you! :)
