### ISSUE TITLE
(TRANSLATION) masterclass page for participant

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#254]
re: https://github.com/ecommerceberlin/ecommerceberlin.com/issues/246

URL is https://ecommerceberlin.com/masterclasses

**Comment by az** [comment]
to help you with FAQ i have revealed this section at TEH - https://targiehandlu.pl/workshops (at the top of the page)

**Comment by klaudia2209** [comment]
@az I think that you mention that there are some translations I can use as well, probably in CSV file (?) where can I find it?
