### ISSUE TITLE
(VARIA) - VIP page with form for vips (edited)

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#256]
Hello, @az I talked to Mark and he really would like to start with sending VIP invitations. He explained me steps and how we should work on it: 

1. To run profile pages 
- [ ] button request a meeting should working 
- [ ] check the confirmation e-mail (request a meeting) if it's ok (do we have a draft somewhere?) 

2. To run VIP invitations on the exhibitors' accounts: 
- [ ] we have to check the confirmation e-mail - do we have a draft somewhere? 
- [ ] if someone gets to the exhibitors profile with VIP invitation (special link), it would be good to remove "request a meeting" and usual form, because it can mislead the users 

3. Adjust the E-commerce Berlin Expo profile for sending VIP invitations. 

- we don't need request a meeting button 
- we can remove usual form 
- we can add some info about benefits for VIPs 

If adjustments on the E-commerce Berlin Expo profile won't be possible, Mark ask for running a temporary page: 
https://ecommerceberlin.com/vip

**Comment by az** [comment]
related https://github.com/ecommerceberlin/ecommerceberlin.com/issues/245

**Comment by az** [comment]
@klaudia2209 in the first place i must FIX standard VIP flow and then i will CHECK if the process i have suggested to Mark will be possible.....this was and is just a theory when we have spoken about it.

**Comment by klaudia2209** [comment]
Ok, I see

**Comment by az** [comment]
@klaudia2209 in the future - such "notes from the meeting" should go to the docs - and we can discuss it (in docs you can comment lines, words etc) ... after i understand every single line (i cannot in this context) we can divide it and create separate GH issues....here we have 4 subjects (PROFILES., VIPS, VIP by EBE, MEETUPS), 3 contexts (IDEA, MAINTENANCE, BUG possibly).....i cannot process such mess.

**Comment by klaudia2209** [comment]
I know, there is a lot of points and steps to do. 

Here is the link to the docs, we can discuss it here: https://docs.google.com/document/d/1DIHuYJC_jImKBCd942Cn7RQ3dkjZdKbi42KBhcBPVl0/edit

**Comment by klaudia2209** [comment]
hej, @az, jak znajdziesz chwilę, prośba o info jak ostatecznie działamy z wysyłaniem zapek VIP. Wiem, że dużo tematów na raz się nagromadziło i się sporo dzieje :)
