### ISSUE TITLE
(TRANSLATION) VIP-related registration status asset ids

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#259]
pasting here as it may be easily skipped

* vipcodes.code-is-expired CODE IS EXPIRED (internal info: was sent to the email address via panel and 24hrs passed)
* vipcodes.status-register (we cannot find such email address among visitors - please register as visitor and you will be upgraded)
* vipcodes.status-assigned (everything ok - we upgraded your status to VIP)

please translate it

**Comment by klaudia2209** [comment]
done
