### ISSUE TITLE
list of benefits for different types of booths

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#26]
as seen on https://live.targiehandlu.pl/ now its possible to assign different set of benefits to different tickets

so? 

Grand?
Partner?
Standard/Hot/SuperHot?

where can i find the list?

![E-commerce Berlin Expo | Berlin | February 24, 2022 2021-06-14 17-20-50](https://user-images.githubusercontent.com/2198/121916977-ee017b00-cd34-11eb-8155-7d36060e8ff9.jpg)

**Comment by jprzybylski4** [comment]
Is this enough? 
<img width="959" alt="tabelka" src="https://user-images.githubusercontent.com/75311923/122056593-05e70680-cdea-11eb-981b-017395856316.png">
