### ISSUE TITLE
(MAINTENANCE) SCHEDULE 2-3 stages?

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#262]
Klaudio, wybadaj proszę co nas powstrzymuje żeby pokazać agendę 2-3 scen (czyli przypisać presentation_time i presentation_venue) 

na ten moment faktycznie musimy każdemu obiecywać złote góry bo na stronie nie ma niczego przyciągającego 

takie mam sloty 
```

 '10:30': 'presentation',
 '11:10': 'presentation',
 '11:50': 'presentation',
 '12:30': 'presentation',
 '13:20': 'presentation',
 '14:00': 'presentation',
 '14:40': 'presentation',
 '15:20': 'presentation',
 '15:50': 'presentation'

```
cc @marek-berlin

**Comment by klaudia2209** [comment]
@az nie znamy jeszcze tematów, w przyszłym tyg. Fabien będzie przypominał o tematach (on zajmuje się agendą i komunikacją masterclassów) ;)

**Comment by az** [comment]
@klaudia2209 mam nadzieje, ze Fabien wie, ze oni POWINNI (moim zdaniem muszą ) sami sobie to uzupełnić ?

ze starego admina do speakerów wysyła się wiadomość z linkiem https://ecommerceberlin.com/recall/[[token]] do tych z tagiem dot speakera (nie dotyczy masterclasses) i mają specjalną stronę do updejtu

Marek z pewnością pokaże co i jak...

**Comment by klaudia2209** [comment]
Ok, to muszę to sprawdzić we wtorek, bo nie wiedziałam o tym
