### ISSUE TITLE
(TRANSLATION) translate masterclasses submission update page 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#265]
@klaudia2209 its URGENT

**Comment by klaudia2209** [comment]
I know, started working on it

**Comment by az** [comment]
![E-commerce Berlin Expo | Berlin | February, 2023 2022-12-27 10-43-48](https://user-images.githubusercontent.com/2198/209647139-33ee1a65-0cdc-4b98-929b-239fa0c842ee.jpg)

**Comment by az** [comment]
@klaudia2209 chyba masz na mysli strone dla participanta ... to inny temat - mniej wazny :) tu strona do edycji zgloszenia zeby miec co pokazac dla participanta :) .... a szczegoly jak sie dostac do takiej edycji wrzucam na slacka

**Comment by klaudia2209** [comment]
Aaa, ok! I tę stronkę wysyłamy prelegentom, tak? Dobrze, działam nad nią w takim razie.

**Comment by klaudia2209** [comment]
What does the avatar mean? Profile picture of the speaker?

**Comment by klaudia2209** [comment]
Translation done
