### ISSUE TITLE
Featured Speakers on HP

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#267]
@klaudia2209 ask @marek-berlin to set featured=1 for exciting and COMPLETE speaker profiles that we want to show on the homepage (as we dont have schedule etc)

**Comment by klaudia2209** [comment]
min. 4 prelegentów, 8 optimum, max. 12 prelegentów

**Comment by az** [comment]
@klaudia2209 mamy to? :)

**Comment by klaudia2209** [comment]
tak, mamy! :)
