### ISSUE TITLE
(BUG) presenters are not visible on presenters page 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#268]
Hello, @az

Could you check if there is everything ok with: https://ecommerceberlin.com/presenters page, please? 

The are presenters missing on the website. Mark said that they were visible previously

**Comment by az** [comment]
@klaudia2209 sprawdzam

**Comment by az** [comment]
@klaudia2209 idzie build z fixem

**Comment by az** [comment]
@klaudia2209 live

**Comment by klaudia2209** [comment]
super, dzięki!
