### ISSUE TITLE
(URGENT BUG) “Promote your company” exhibitors have banners from Targi eHandlu

### ISSUE THREAD

**Issue by marek-berlin** [ecommerceberlin/ecommerceberlin.com#271]
“Promote your company” exhibitors have banners from Targi eHandlu. It is a mistake. besides, we are not supposed to make it available until February, and it is added in the January tab.

**Comment by az** [comment]
Marek - o to chodzi? sam piszesz o "lost in translation" wiec moze nie silmy sie o jezyk angielski skoro kazdy nazywa rzecz X po swojemu

o to chodzi?

![E-commerce Berlin Expo 2023-01-03 20-43-46](https://user-images.githubusercontent.com/2198/210429886-a1a9d303-c815-43fa-a8c4-a78117553b2d.jpg)

**Comment by az** [comment]
@marek-berlin niewiadomo o co chodzi...zajelo mi to 10 minut zeby namierzyc 

1. i chodzi o logistics /..... oryginalnie ta zakladka (ktora zawiera promote) nazywa sie "3weeks" .. taki jest asset id - skontaktuj sie z kims kto postanowil to przetlumaczyc tak jak to zostalo przetlumaczone
2. nie ma takiego labela jak URGENT BUG .... to ze se pykniesz jakies slowko to nie znaczy ze sie cos zmaterializuje
3. btw: BUG to problem techniczny 
4. issue ma charakter MAINTENANCE (czyli jakas zmiana...) ot ktos przeoczyl ze jest aktywny link do podstrony ktora jako taka nie funkcjonuje w menu
5. sorry ale musze Cie usunac z collabow bo mam po raz 10x dejavu ze jade od poziomu przedszkola z tematami
