### ISSUE TITLE
(Maintenance) checkbox missing - visitors form

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#272]
I got the info that there is no checkbox on EBE website under the registration form: 

"I confirm that I have read and I accept the Terms & Conditions" (there is something like this on EGA).

**Comment by az** [comment]
nie bądź gońcem i nie duplikuj tematów please... taskiem nr 1 bylo zapoznanie sie z issues 

https://github.com/ecommerceberlin/ecommerceberlin.com/issues/152
