### ISSUE TITLE
(QUESTION) how to handle double profiles on the speakers' page

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#273]
Hej, @az 

Dostałam info od Fabiena, że jeśli prelegent ma swoje przemówienie i dodatkowo występuje w panelu, musi posiadać dwa konta, żeby wyświetlały się obie atrakcje - OK. Ale na stronce "speakers" ten sam prelegent pojawia się dwa razy, bo występuje tu i tu i wygląda to jak błąd. 

Czy możemy jakoś to zmienić, coś z tym zrobić? 

![image](https://user-images.githubusercontent.com/118257251/211764653-d0f47d43-8ad7-4c26-aa48-7670af448a7b.png)

**Comment by az** [comment]
@klaudia2209 dla takich kejsow stworz prosze issue (MAINTENANCE) exclude speaker from list .... i w komentarzach ID tego co ma byc wykluczone (powtarzam..... ID...nie nazwisko )

**Comment by az** [comment]
![filtered?tags=speaker 2023-01-11 10-45-10](https://user-images.githubusercontent.com/2198/211786631-5856eab8-340f-4c08-8be8-b952009022bd.jpg)

wykluczam po tym ID

**Comment by klaudia2209** [comment]
Hej, 
podsyłam listę zduplikowanych prelegentów:

Anna Graf
166323
165801

Jens Brämer
163534
163526

Kerstin Zerbe
163533
163530

Urs Rahne
166265
166264

**Comment by az** [comment]
@klaudia2209 



`@klaudia2209 dla takich kejsow stworz prosze issue (MAINTENANCE) exclude speaker from list .... i w komentarzach ID tego co ma byc wykluczone (powtarzam..... ID...nie nazwisko )`

czyli osobne issue .... liste ID co ma byc wykluczone.... x,y,z .... (bo moze 1 profil z 2 jest niekompletny wiec lepiej zeby nie zostal wykluczony losowo przez moj wybor)

**Comment by az** [comment]
poza tym zakladam ze wszyscy z masterclasses maja byc wykluczeni ... ich ID sa znane.. zrobmy zatem 1 dzialanie zeby do tego nie wracac

**Comment by klaudia2209** [comment]
Ok, dodaję issue
