### ISSUE TITLE
(TRANSLATION) adapt all translations to new VIP strategy

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#274]
<img width="984" alt="E-commerce Berlin Expo invites you to a meeting at the E-commerce Berlin Expo 2023-01-11 12-28-29" src="https://user-images.githubusercontent.com/2198/211806547-e641801d-f7fe-4319-91e2-d670af7bcbdd.png">

zgodnie z ustaleniami zmien prosze WSZYSTKIE tlumaczenia (oprocz tych ktore dotycza zapek VIP) zeby nie wprowadzaly w blad

**Comment by klaudia2209** [comment]
Jak mogę sama wejść w taki widok, żeby sprawdzić, co tam należy jeszcze przetłumaczyć?

**Comment by az** [comment]
fajnie...a wszedzie indziej sprawdzalas ? (strefa zostaje tylko w odniesieniu do zapek VIP).
