### ISSUE TITLE
(TRANSLATION) translate meetup feature (participant-to-exhibitor)

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#275]
<img width="805" alt="E-commerce Berlin Expo invites you to a meeting at the E-commerce Berlin Expo 2023-01-11 12-30-17" src="https://user-images.githubusercontent.com/2198/211806848-1ef27674-bd8d-45e2-89d8-425f7f0c658d.png">

**Comment by klaudia2209** [comment]
nie mam pewności do czego odnoszą się te statusy, więc dodałam takie treści w localise, prośba o potwierdzenie czy są ok. 

exhibitors.meetup.statuses.assigned - You are assigned to the meeting 
exhibitors.meetup.statuses.register - Registration for the event

**Comment by az** [comment]
@klaudia2209 no to sa bez sensu

dalem Tobie pliki z tlumaczeniami z TEHu - nie mozesz tam tego odszukac?

**Comment by az** [comment]
[account-bundle (1).csv](https://github.com/ecommerceberlin/ecommerceberlin.com/files/10393208/account-bundle.1.csv)
[public-bundle.csv](https://github.com/ecommerceberlin/ecommerceberlin.com/files/10393209/public-bundle.csv)

**Comment by az** [comment]
> You are assigned to the meeting
pomijajac ze ja tego nie rozumiem (obawiam sie ze znaczna czesc populacji takze nie zrozumie) to jak to sie ma do faktu ze EXH podejmuje decyzje i moze kliknac reject? ..... to jest po prostu wyslanie zaproszenia do wystawcy

**Comment by az** [comment]
<img width="1088" alt="public-bundle 2 2023-01-11 14-28-46" src="https://user-images.githubusercontent.com/2198/211831927-988c5550-f2b0-47ec-aee2-b7f210f5df94.png">

juz ustalalismy ze bazowo masz brac tlumaczenia z TEHu...kazde silenie sie na oryginalnosc przynosi tylko cierpienie :)

**Comment by az** [comment]
@klaudia2209 done?

**Comment by klaudia2209** [comment]
done
