### ISSUE TITLE
(MAINTENANCE) separate flow for STAGE E

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#277]
Hej, 

w nawiązaniu do rozmowy z Fabienem - prośba o utworzenie osobnego flow dla sceny E (grafika / podstrona)

**Comment by az** [comment]
@klaudia2209 podstronke mozna ogarnac - ale prosze o finalne potwierdzenie ze temat E jest zamrozony

grafika po stronie grafika

**Comment by klaudia2209** [comment]
co do sceny E - agenda jest potwierdzona, więc z naszej strony mamy pewne info, pytanie jakie mamy możliwości i czego od nas potrzebujesz i w jakiej formie ;)

**Comment by az** [comment]
@klaudia2209 co do E ... imo najlepsze beda 3x bannery i pod normalna (ABCD) agende bo system nie wspiera tego co wymyslil Fabien 

banerki powinny byc w plikach wektorowych w 3 proporcjach (szerokosc vs wysokosc)

3:1 
2:1
1:1

jesli tego nie kumasz to podbij - wytlumacze
