### ISSUE TITLE
(BUG) RVPS mixed with Przeglądaj uczestników

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommerceberlin.com#280]
Kiedy nie ma żadnych zaproszeń w RVPs pojawia się zawartość strony "Przeglądaj uczestników", po pojawieniu się zaproszeń - ta zawartość znika i jest zastępowana zawartością RVPs. 

Wystawca pyta dlaczego nie widzi już pełnej listy po wysłaniu zaproszenia 

Słowami Piotra - "Browse participants są podlinkowane w pierwszym widoku RSVPs", ale nie ma widocznej zakładki "Browse participants" na stałe

Przykład: 
wystawca z zaproszeniami / masterclassami: 
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/118257251/212921589-de69b631-0bb3-4ae9-96e6-c1be57f705ef.png">

wystawca bez zaproszeń: 
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/118257251/212921903-ac86bdf5-7f9a-4f46-9f63-0c24edbfd6d4.png">

po kliknięciu +ADD
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/118257251/212922038-9eb122cb-67c8-42ea-8572-56440c849826.png">

**Comment by az** [comment]
to nie jest BUG tylko kwestia interfejsu.... po prostu przegladaj bylo udostepniane zwykle wczesniej (bo innych rzeczy nie bylo)....a "przegladaj uczestnikow" to nie jest cos co udostepniamy.

zmienie opis dla widoku pustego....

**Comment by az** [comment]
@klaudia2209 dlaczego to w ecommerceberlin dodalas? co to ma wspolnego ze strona publiczna skoro wklejasz screeny z account?
