### ISSUE TITLE
(MATERIALS) baner dot sceny E na podstrone /schedule

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#283]
w nawiazaniu do https://github.com/ecommerceberlin/ecommerceberlin.com/issues/277

**Comment by KarolinaTEH** [comment]
@az wytłumaczysz please co dokładnie trzeba przygotować? 
co ma się znaleźć na banerkach? 
nie potrafię sobie tego zwizualizować

**Comment by az** [comment]
@KarolinaTEH grafika (3x proporcje - pod roznych klientow www,tablet,telefon), ktora promuje https://www.creatorsofthemetaverse.de/fest/

czyli ktos jest u nas, wychodzi na inne www zeby sprawdzic czesc agendy e i wraca do nas zeby sie zarejestrowac
debilny flow ale jak sie zostawia wolna reke pt "rob agende" i nie przekaze temu komus ze godziny musza byc fixed to powstaja takie kwiatki

**Comment by az** [comment]
jesli to nie beda pliki wektorowe (wtedy rozmiar nie ma znaczenie a proporcje....4:1 2:1 1:1) a bitmapy to przykladowe rozdzialki to 

1200x300
1200x600
1000x1000

**Comment by KarolinaTEH** [comment]
dzięki - wszystko jasne. Ola będzie działała

**Comment by KarolinaTEH** [comment]
@az link do grafik: https://drive.google.com/file/d/1Mik5k8KBcVPAHkT2Ia3zK2RExjLMblPp/view?usp=share_link

**Comment by az** [comment]
@KarolinaTEH to jest 1 plik zamiast 3..co mam z tym zrobic?

**Comment by KarolinaTEH** [comment]
@az wkleiłam nie ten link. Tu poprawny: https://drive.google.com/drive/folders/1xBcwsYmc3m7MnwP6N4y7CJjOzn-uCT0I?usp=share_link
