### ISSUE TITLE
(MAINTENANCE) masterclasses - disable 'apply' button 

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#285]
@az harmonogram dot. startu zapisów na warsztaty:
- do 31.01 - copy maila
- 7.02 - wysyłka
- 9.02 - start zapisów
prośba tylko, żebyś wyłączył teraz możliwość zapisywania się

**Comment by az** [comment]
wylacze jak ogarne ograniczenie dot 1 zapisu per participant

**Comment by KarolinaTEH** [comment]
@az 
**participant accepted** -> przychodzi mail z TEH. Tu tłumaczenia EN+DE: https://github.com/ecommerceberlin/ecommerceberlin.com/issues/243
**participant rejected** -> nie przychodzi żaden mail. Tłumaczenia EN+DE: https://github.com/ecommerceberlin/ecommerceberlin.com/issues/244

**Comment by KarolinaTEH** [comment]
na /masterclasses:
- awaiting -> działa
- remaining seats -> 'NAN'

**Comment by az** [comment]
@KarolinaTEH dzięki.

**Comment by az** [comment]
@KarolinaTEH w nawiazaniu do KNS (komunikacji na slacku :) prosba o potwierdzenie testu #2.

**Comment by KarolinaTEH** [comment]
@az mail z potwierdzeniem akceptu na warsztaty - błąd w placeholder
![image](https://user-images.githubusercontent.com/80756258/215696549-4ad569b7-004d-4910-820e-03cfb6c9caab.png)

**Comment by KarolinaTEH** [comment]
@az przy zapisie na warsztat uczestnika, który nie jest jeszcze zarejestrowany na event zgłoszenie jest traktowane jako zapka P2C. 
![image](https://user-images.githubusercontent.com/80756258/215699608-7c9688e0-8fe9-424d-b776-6daffc293821.png)
