### ISSUE TITLE
organizer's VIPs - provide list of allowed vipcodes

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#287]

**Comment by az** [comment]
@KarolinaTEH potrzebowalbym liste kodow (najlepiej skojarzonych z typem partnera czy typem bazy) ktore moga sie rejestrowac jako vip...te kody oczywiscie beda mogly byc przekazane juz w URLu

cos jak partner_abc, partner_xyz, jakis string ktory wiadomo ze odpowiada bazie np duzych sklepow...

**Comment by KarolinaTEH** [comment]
@az lista kodów: https://docs.google.com/spreadsheets/d/1ieSZpkkRENfThvOnIvN_BeWL2O4F2soXK9NENb4lpAw/edit?usp=sharing

MT: Kody są oczywiście wymyślone. Nie chciałem podawać źródła bazy w ramach niektórych kodów bo jasno by wskazywały jak te bazy powstały... a to nie było by nic dobrego

**Comment by az** [comment]
@KarolinaTEH danke.... tak max 20 moge wklepac bo robie to recznie... poki co jest 11 wiec ok ;)
