### ISSUE TITLE
(MAINTENANCE) removing visitors from the database

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#288]
@az lista osób do usunięcia: https://docs.google.com/spreadsheets/d/1R1itvgFD6fLv1mbGSIZkl1vO3ZCvpr4opwpbC5MLrK8/edit#gid=1221321762

**Comment by az** [comment]
@KarolinaTEH nie przetwarzam takich rzeczy.... prosze o przedzial od ID do ID

**Comment by KarolinaTEH** [comment]
done (usunięte ręcznie)
