### ISSUE TITLE
organizer's VIPs- confirm benefits

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#289]
![E-commerce Berlin Expo | Berlin | February, 2023 2023-01-23 16-28-00](https://user-images.githubusercontent.com/2198/214079281-08110441-c8c5-4f58-80cf-906f96ecdd06.jpg)

z dyskusji wyszlo ze dajemy BADGE'a VIP a reszta idzie won - ale jednak fajnie wydumac jakies korzysci? :)

better networking? 
better interacting with exh?

**Comment by KarolinaTEH** [comment]
_Premium Badge (better networking with exhibitors w opisie)
Fast-entry (to jestesmy w stanie dowiezc more or less - omowione z PSZ)
First access to all recordings from the conference (moge to dowiezc bez wiekszego problemu)_ - @az tu potwierdź proszę, że będzie możliwość wygenerowania listy osób, które się zapisały, np. po referral code na liście visitorsów 
jeśli tak, to Marek przygotuje copy
