### ISSUE TITLE
(TRANSLATE) translate updated vip benefits

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#290]
![E-commerce Berlin Expo | Berlin | February, 2023 2023-01-24 10-49-47](https://user-images.githubusercontent.com/2198/214260586-482cd444-e629-4ecd-b6b9-b0af01931d00.jpg)

preview https://ecommerceberlin.com/partners/test123

**Comment by az** [comment]
@KarolinaTEH mozesz nie robic tak albo nie pozwalac aby tlumaczenia nie pokrywaly sie z labelami? 

jak chce sie zmienic kolejnosc to tworzy sie issue (MAINTENANCE) change the order of vip benefits

do poprawki

**Comment by az** [comment]
bo to nie jest benefit1 benefit2.....bede chcial gdzies uzyc danego tlumaczenia w innym widgecie i bede robil dochodzenie i tracil czas....  nienawidze takich "hackow"

**Comment by KarolinaTEH** [comment]
jasne, rozumiem i przy tłumaczeniach, które ja robię zwracam na to uwagę.
Zajmując się tym + TEH nie jestem w stanie z defaultu sprawdzać tego typu szczegółów, nie starczyłoby mi na to doby

**Comment by KarolinaTEH** [comment]
@az poprawione
