### ISSUE TITLE
(BUG) Markdown is not supported in exhibitors' public profiles

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#293]
example: https://ecommerceberlin.com/exhibitors/dellcom  

![image](https://user-images.githubusercontent.com/80756258/215442533-c0651d6f-6705-4b71-a0fe-b083a0be6fa8.png)

@az

**Comment by az** [comment]
@KarolinaTEH generalnie dubel z https://github.com/ecommerceberlin/exhibitors/issues/45 

temat znany ale jeszcze nie badany co do najlepszego rozwiazania

**Comment by az** [comment]
@KarolinaTEH właczam markdown na EBE...... bardzo prosze by sie tutaj nie pojawil issue (BUG) powrotny (AM musza wiec o co chodzi o ogarniac temat.....albo wejsc w account i poprawic opis albo poprosic o to firme)
