### ISSUE TITLE
Regarding admin - Prepare cloned tickets for future sales rounds

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#30]
Ideally, we would need 2 more tickets per each of 5 booth categories = 10 more tickets total

**Comment by az** [comment]
done

https://pages.ecommerceberlin.com/admin/ticketedit?ticket_id=1920
(...)
https://pages.ecommerceberlin.com/admin/ticketedit?ticket_id=1929
