### ISSUE TITLE
(TEST) P2C i LTD ("masterclasses") invitations for current and new visitors

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#300]
@KarolinaTEH 

re: https://github.com/ecommerceberlin/ecommerceberlin.com/issues/296 i re: https://github.com/ecommerceberlin/ecommerceberlin.com/issues/285

niestety naprawa tego mogła przynieść regresje dot zapek P2C stad prosba o przetestowanie 4 scenariuszy

* non-visitor chce sie umowic na spotkanie
* visitor chce sie umowic na spotkanie
* non-visitor chce sie zglosic na warsztat
* visitor chce sie zglosic na warsztat

w komciach daj mi znac co pozniej wyczyscic (rowniez apropos wczesniejszych testow)

**Comment by KarolinaTEH** [comment]
@az

- non-visitor chce sie umowic na spotkanie - rejestracja OK, ale nie wyświetla się w RSVPs
- visitor chce sie umowic na spotkanie - OK
- non-visitor chce sie zglosic na warsztat - rejestracja OK, ale nie wyświetla się w RSVPs
- visitor chce sie zglosic na warsztat - OK

Testowałam na FedEx i Mondu:
hrqjkvd977@tmail9.com
wasyfze583@tmail9.com
karolina.broniarz@gmail.com
karolinabroniarz@gmail.com
karolina.michalak@targiehandlu.com.pl
karolina.michalak@targiehandlu.pl

+ widzę testy Klaudii na everstox:
klaudia.chomiak95@gmail.com

**Comment by az** [comment]
@KarolinaTEH chyba znalazlem fuckup.... prośba o potworzenie testu (wierze ze po raz ostatni)

tylko scenariusze Non-visitor dla LTD/"masterclasses" i P2C

**Comment by az** [comment]
@KarolinaTEH poszedl maly update kodu...... wiec prosba o ponowny test 

tylko scenariusze Non-visitor dla LTD/"masterclasses" i P2C....czy wchodzi to do RSVP czy nie

**Comment by KarolinaTEH** [comment]
@az działa, wyświetla się w RSVPs

testy na Mondu - nowe maile:
uruwwbb739@tmail3.com
tnorljo983@tmail9.com
eqmfdav733@tmail9.com
hfeooqi568@tmail3.com
