### ISSUE TITLE
(TRANSLATION) masterclasses - some less visible items

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#301]
@KarolinaTEH sprawdz prosze czy sa przetlumaczone:

"workshops.apply.closed"  (nie pokazywalo sie bo nie wyczerpal sie limit 

"workshops.apply.disabled"- swiezo dodane bo opcji ukrywania w ogole nie bylo...na TEHu zapisy powstaly just-in-time :D

**Comment by KarolinaTEH** [comment]
done
