### ISSUE TITLE
(GFX) provide updated gfx for "share with friends that you are going to EBE"

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#309]
![E-commerce Berlin Expo | Berlin | February, 2023 2023-02-07 16-21-39](https://user-images.githubusercontent.com/2198/217286494-cc980271-9f55-45c6-aece-9dc71d0d3a03.jpg)

**Comment by KarolinaTEH** [comment]
@az just to be 100% sure: 
- proporcja jak przy aktualnej grafice -> 1,9:1 (wymiary 960x504 px)
- automatycznie dodaje się tylko napis -> CU! [fname] from [cname]. Cała reszta, łącznie z żółtym polem pod nim to część grafiki, którą mamy dostarczyć

**Comment by KarolinaTEH** [comment]
@az 

Tekst: Meet me at the Expo! [fname] from [cname]

[Meet Me banner_02 (1).pdf](https://github.com/ecommerceberlin/ecommerceberlin.com/files/10708603/Meet.Me.banner_02.1.pdf)
![Meet Me banner_02 (1)](https://user-images.githubusercontent.com/80756258/218124550-617f2b28-1325-4905-8a2a-9901b615f3f0.jpeg)
