### ISSUE TITLE
(UPDATE) ticket and vip ticket additional info 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#310]
tła dot ticketów

najlepsze będzie info CO ZMIENIĆ/DODAĆ (tekst).... pliki niechętnie gdyż musze je mieć przygotowane pod konkretny generator

[ebe6_ticketdownload_vip.pdf](https://github.com/ecommerceberlin/ecommerceberlin.com/files/10676717/ebe6_ticketdownload_vip.pdf)

[ebe6_ticketdownload.pdf](https://github.com/ecommerceberlin/ecommerceberlin.com/files/10676718/ebe6_ticketdownload.pdf)

**Comment by az** [comment]
mogę np przyjąć mapkę ..... tak czy siak potrzebuję tylko i wyłącznie TEKST albo poj. elementy w wektorach (PDF, SVG)

**Comment by KarolinaTEH** [comment]
_**Upper half of the page**_

Visitor’s badge x2

_**In the middle of the page**_

Fold and insert into a badge holder, available on arrival at the Event

_**Left bottom corner**_

WELCOME TO THE E-COMMERCE BERLIN EXPO! 

HOW TO USE YOUR E-BADGE 

To ensure a seamless experience at the event, please follow these instructions for using your e-badge: 
1. Print this page clearly on A4 paper and bring it with you to the venue. 
2. Upon arrival, head directly to the entrance to be scanned in. 
3. Badge holders and lanyards will be available at the entrance. 
4. If you lose or forget your e-badge, visit the registration kiosk to have it reprinted. Please note that not having your badge may result in a delay at the entrance. 

**FOLLOW US ON SOCIAL MEDIA** 

Stay up-to-date with all the latest happenings at the event! Follow us on our social media platforms, and don't forget to tag us using the official event hashtags. We can't wait to see your posts! 

#EcommerceBerlinExpo2023 #EBE2023 #EcommBerlin

_**Right bottom corner**_

**VENUE**

STATION Berlin
Luckenwalder Str. 4-6
10963 Berlin, Germany

**OPENING TIME**

Thursday, 23rd February 2023, 10:00-17:00

**REACHING THE EVENT**

Consider using public transportation - the nearest U-Bahn station is called "Gleisdreieck".
If driving, there is a nearby car park, "Parkhaus Gleisdreieck" (entry via Schönenberg Strasse) available for your convenience. Parking fees may apply.

**CONTACT**

visitors@ecommerceberlin.com

**THANK YOU FOR CHOOSING TO JOIN US!**

example: 

![image](https://user-images.githubusercontent.com/80756258/217878492-c368ea18-7572-4d01-a1c1-65305dfbe526.png)

**Comment by KarolinaTEH** [comment]
[BrightData_Logo.pdf](https://github.com/ecommerceberlin/ecommerceberlin.com/files/10699526/BrightData_Logo.pdf)
