### ISSUE TITLE
(MAINTENANCE) asset update at /invites

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#316]
@az wszystko wydaje się być ustawione poprawnie w localise (dodany asset visitors.invite.description), ale nie zaciąga się na stronę. 
na TEH taka sama sytuacja 

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/80756258/219359383-a019001c-5551-443c-beaf-8dfa30c4982f.png">

https://ecommerceberlin.com/invites/169322

**Comment by az** [comment]
@KarolinaTEH idzie build ...... jak będzie completed na kanale _it to zerknij please czy sie poprawiło :)

**Comment by KarolinaTEH** [comment]
działa, dzięki
