### ISSUE TITLE
(MAINTENANCE) tickets IDs to be disabled from EB sales

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#324]
IDs ticketów: TOP30#1 i TOP30#2: 

2383, 2465, //STD
2380, 2467, //HOT
2412, 2456, //SH
2417, 2469, //ULTRA
2400, 2468, //GRAND
2393, 2466, //P GRAND

**Comment by az** [comment]
@KarolinaTEH danke
