### ISSUE TITLE
(QUESTION) sales team

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#326]
Lucas gone so any changes? 

<img width="613" alt="E-commerce Berlin Expo | Berlin | February, 2023 2023-03-06 22-35-21" src="https://user-images.githubusercontent.com/2198/223236211-01cf6390-2bb3-4158-a2e5-9b670c7599e1.png">

**Comment by KarolinaTEH** [comment]
@az please change it to:

Gerome 
Business Development Manager 
hello@ecommerceberlin.com
+49 305 201 42 88

https://res.cloudinary.com/ecommerceberlin/image/upload/v1678187389/Website/gerome.jpg

and remove Peter

**Comment by az** [comment]
> Business Development Manager 

this is a person who looks for partnerships, alliances IMO....such label is misleading
