### ISSUE TITLE
icons for external services are overlapping

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#33]
![E-commerce Berlin Expo | Berlin | February 24, 2022 2021-07-05 22-43-41](https://user-images.githubusercontent.com/2198/124516679-847c0600-dde2-11eb-88db-2dee2a9f497f.jpg)

**Comment by az** [comment]
@marek-berlin can u resolve this via GTM config pleasE?

**Comment by marek-berlin** [comment]
done, nie wiem gdzie moge to oznaczyc jako finished.
