### ISSUE TITLE
(MAINTENANCE) update legal files

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#332]
[exhibitors.md](https://github.com/ecommerceberlin/ecommerceberlin.com/files/10933060/exhibitors.md)
[visitors.md](https://github.com/ecommerceberlin/ecommerceberlin.com/files/10933492/visitors.md)
[visitors_data.md](https://github.com/ecommerceberlin/ecommerceberlin.com/files/10933518/visitors_data.md)
[imprint.md](https://github.com/ecommerceberlin/ecommerceberlin.com/files/10933575/imprint.md)

**Comment by az** [comment]
@KarolinaTEH  fascynujace ze plik zrodlowy to visitors-data a dostaje zwrotnie visitors_data :)
