### ISSUE TITLE
(MAINTENANCE) tickets IDs to be disabled from TOP30 sales

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#335]
2382, 2381, 2451, 2379, 2384, 2373, 2402  //STD
2378, 2411, 2377, 2375, 2429, 2443, 2394, //HOT
2386, 2388, 2389, 2390, 2391, 2431, 2444, //SH
2419, 2415, 2420, 2422, 2423, 2430, 2457, //ULTRA
2397, 2458, 2459, 2460, 2461, //GRAND
2398, 2395, 2462, 2463, 2464, //P GRAND

**Comment by az** [comment]
@KarolinaTEH sprawdz please czy OK

**Comment by KarolinaTEH** [comment]
@az wszystko wyświetla się OK
