### ISSUE TITLE
(IDEA) adding video to services descriptions at /premium

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#340]
videos are ready (https://drive.google.com/drive/folders/1-xnOieSrn67jqtvB7BBmvINybUsYtMDb) and will be uploaded to youtube as well
@az could you please enable videos embedding in the description box?

**Comment by az** [comment]
@KarolinaTEH - i cannot proceed with such data/info

steps 

* upload them to YT or vimeo
* paste corresponding video links (to YT or vimeo .... link to human page - not an embed code) to item's description
* create an issue that it is ready to be parsed
