### ISSUE TITLE
(IDEA) visitors registration form changes

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#342]
@az a complete version of the updated regform below (new fields are marked in italics)

1. Work Email * 
2. First name *
3. Last name *
4. Company name *
5. Position in the company *

*6. Country calling code* (dropdown list)*

7. Mobile Phone number * 

*8. Your Linkedin profile URL (optional)*

*9. Type of participation - Please select one of the following* (dropdown list)*
- I work for a retailer/merchant/wholesaler/marketplace
- I work for a brand/manufacturer
- I work for an agency or service provider (vendor)
- I am a consultant
- I am a webmaster/developer
- I am press/media/blogger
- I am a student/teacher/academic

*10. Job level - Please select one of the following* (dropdown list)*
- Student
- Entry Level (0-2 years)
- Manager (2-5 years)
- Professional (over 5 years)
- Head of Department
- Director
- C-level
- Board Member
- Others

*11. By submitting this you agree to our privacy policy and consent to receiving communications. You may opt out anytime.* (checkbox)*

**Comment by KarolinaTEH** [comment]
1. Work Email - i’d be great if this field could verify the email address and reject the most popular private mail providers: 
gmail.com
web.de.
gmx.net.
live.com.
mail.ru.
gmx.de.
hotmail.com
outlook.co

6. Country calling code - input:
49 Germany
41 Switzerland
43 Austria
31 Netherlands
32 Belgium
33 France
34 Spain
353 Ireland
39 Italy
420 Czech
421 Slovakia
44 UK
45 Denmark
46 Sweden
48 Poland
972 Israel
1 United States
OTHER


9. Type of participation - It is important to have the ability to send tickets to a selected group only

(It could be shortened to a simple: retiler, provider, media, student, but it wouldn’t give us the possibility to exclude consultants and developers while sending tickets)

**Comment by az** [comment]
@KarolinaTEH in the future i will reject such "here is my dream list" issues...there are 3 issues here ...

* modify regform
* provide targeted sending capability 
* exclude domains

development is not writing essays... ISSUES MUST BE ATOMIC
