### ISSUE TITLE
new dates for CFP timeline

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#35]
https://ecommerceberlin.com/speaking

**Comment by jprzybylski4** [comment]
Submissions - 01.09 - 30.09
Internet Users’ public voting - 1.10 - 20.10 
Public voting Nominees announcement - 21.10 
Advisory Board voting - 22.10 - 28.10
Winners Announcement - 29.10

**Comment by az** [comment]
a2bd1a167101c30a3bf2996b861e8afec22851e2
