### ISSUE TITLE
(MAINTENANCE) /premium -> 'soldout' backgroundImage update

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#352]
@az new image https://res.cloudinary.com/ecommerceberlin/image/upload/v1684149426/Website/PREMIUM%20SERVICES/sold-out.png

**Comment by az** [comment]
<img width="614" alt="index js — ecommerceberlin (obszar roboczy) 2023-09-11 11-50-52" src="https://github.com/ecommerceberlin/ecommerceberlin.com/assets/2198/399a19e4-7659-4cd9-9e10-c074437a04bd">

ogarniete zeby szlo via settingsy

(musisz odswiezyc forka masterem.... i w terminalu w folderze pyknac "npm update" ... bo zmienila sie numeracja wersji zewn. biblioteki "site-components" )
