### ISSUE TITLE
(MAINTENANCE) add options to WidgetVisitor

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#358]
@az WidgetVisitor (without VIP) is still being used on some pages
Could you please add 'options' to this widget?

```
options={{
            participant_type: [
                "retailer_wholesaler",
                "brand_manufacturer",
                "service_provider",
                "consultant",
                "developer",
                "media",
                "student"
            ],
            company_role: [
                "student",
                "entry",
                "manager",
                "professional",
                "head_of_department",
                "director",
                "c_level",
                "board_member",
                "other"
            ]
        }}
```

**Comment by KarolinaTEH** [comment]
it's like this now: <img width="924" alt="image" src="https://github.com/ecommerceberlin/ecommerceberlin.com/assets/80756258/75eeb51d-ecbb-422e-9aef-c3f0f73c380d">

**Comment by az** [comment]
@KarolinaTEH there is nothing for me to do 
just create "decorated" WidgetVisitor in composition and customize it with options and use it wherever you want to

to be specific...just copy/paste  "WidgetVisitorWithVip" name it somehow and remove "right={ }" property
