### ISSUE TITLE
(MAINTENANCE) add a subdomain for mailings

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#372]
http://ecommberlin.com/ or simmilar

**Comment by KarolinaTEH** [comment]
@az this domain is needed for December mailings (for promoting EGA submissions and visitors communication) so it'd great to have it in the upcoming days

**Comment by az** [comment]
2024.ecommberlin.com i 2024.ecommberlin.de

**Comment by az** [comment]
do google workspace dodane jako niezalezne domeny (odpowiedzi w ramach kont trzeba przekierowac na inne skrzynki)
do zrobienia przekierowania na strone glowna EBE
