### ISSUE TITLE
(IDEA) hide 'request a meeting button' on PageCompany

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#375]
@az I assume that it should be removed from WidgetCompany.js, but I'm not able to create a PR with changes to this file.

commenting it here doesn't work
<img width="662" alt="image" src="https://github.com/ecommerceberlin/ecommerceberlin.com/assets/80756258/27e6cebb-c611-4d8e-9923-c17a99541786">

**Comment by az** [comment]
@KarolinaTEH why it should be removed?.... too early? i may move enable/disable state to settings

**Comment by az** [comment]
plz provide screenshot with the PR error. are you pulling and merge from master before beginning some work? if not and you have local changes you can STASH THEM (some king of clipboard), pull and merge from master and UN-STASH your changes (of course merge errors may reveal....but after addressing them you will be able to make PR etc)

**Comment by KarolinaTEH** [comment]
@az exactly, it's too early. For example there was a case of the exhibitor sending a newsletter with a link do their profile and invitation to schedule a meeting via this button 

there is no error - there is just nothing happening in the local preview (and it worked when I changed WidgetCompany.js but I don't see this changes in the github desktop and I'm not able to create a PR)

<img width="1275" alt="image" src="https://github.com/ecommerceberlin/ecommerceberlin.com/assets/80756258/3121c90f-094e-4d76-b62b-4ac6c79a3a00">


the other solution is just enabling RSVPs tab in the panel (they'd have to start receiving email notifications), but it'd be great anyway if you could move enable/disable state to settings

**Comment by az** [comment]
@KarolinaTEH ok, i will move visibility state to settings

**Comment by az** [comment]
settings -> exhibitors/disableMeetups affects
* visibility of the button on the salesmap booth details overlay
* visibility of the button on the profile
* visibility of the form when exhibitors/...?meet URL is used (promo materials)
