### ISSUE TITLE
(MAINTENANCE) masterclasses changes (according to TEH)

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#386]
changes to be implemented:
1. Rejection messages crafted by trainers
2. Limiting possibility of registration to 1 workshop at a specific hour slot
4. The number of workshops a participant can apply for = number of available slots 
5. Automatic rejection of remaining submissions after receiving approval for 3 workshops
6. Participants can review accepted workshops and scheduled meetings (https://targiehandlu.pl/todo/[[email]])

TEH vs EBE
venues: 3 -> 2
hour slots: 6 -> 9 (I'll adjust specific times)
participants: 25 -> 40

submissions start planned for: February, 5

**Comment by az** [comment]
parameters:

participants: 25 -> 40 **SET** (frontend + account)

**Comment by az** [comment]
1-5 are implemented (as this is same codebase)

**Comment by az** [comment]
@KarolinaTEH from what i remember we must implement "resignation procedure" ... do you have an idea how we could add missing participants? i have no one convincing idea (we can leave the process as is but when all members will be autorejected after crossing 40 members it would not work)

**Comment by KarolinaTEH** [comment]
@az how about a waiting list? For example, the organizer selects an additional 10 people who will fill in the vacant spots in case of resignation. There shouldn't be an issue with scheduling conflicts since participants can only sign up for one workshop at a given time. And on the 'todo' list, there could be information that certain registrations are pending

**Comment by az** [comment]
@KarolinaTEH sounds good but....it seems too complicated from the technical point of view (we now have 3 states .... not reviewed or reviewed - unaccepted or reviewed - accepted .... if the limit is reached every not reviewed becomes reviewed - unaccepted .... 
easier/ quicker would be repeat standard process BUT all those automatically rejected would be pissed off.....

think about it please...maybe you will come up with other ideas

**Comment by az** [comment]
if someone get autorejected they receive email message... can enroll to different workshop...so in your idea we would have to test if someone enrolled to conflicting (time) after being autorejected etc....  too many areas that can fail :)

**Comment by az** [comment]
maybe we should stick to standard process.... if there are some places left, tutor could and should promote it on their channels and people could enroll......

**ohhh...... we could make possible re-enrolling when being AUTO-rejected? (that is difficult but seems doable)**

**Comment by KarolinaTEH** [comment]
and maybe we could send notifications to those automatically rejected individuals about newly available spots in that case? (for example if there are >4 available, not to spam them)
something like 'back in stock' in eshops

**Comment by KarolinaTEH** [comment]
and maybe we could send notifications to those automatically rejected about newly available spots in that case? (for example if there are >4 available, not to spam them)
something like 'back in stock' in eshops

**Comment by KarolinaTEH** [comment]
@az updated timeline:
6.02 - e-mail to Exhibitors (MT)
7.02 - submissions start
**7.02 - message to all visitors
12.02 - reminder to all visitors** 
14.02 - official end of submissions and deadline for reviewing applications
15.02 - logistics info for Exhibitors (MT)
19/20.02 - logistics info for MS attendees (MT)

questions:
1. to be 100% sure - rejection message with ltd_reject_template will be also sent when the seats limit is reached? or do they have to click 'reject' to send it?
2. what if ltd_reject_template is not added? 
3. is it possible that turning on submissions needs to be done somewhere in API? because nothing happens when I change it here:
<img width="206" alt="image" src="https://github.com/ecommerceberlin/ecommerceberlin.com/assets/80756258/e1f8f9de-9af6-4d6e-98a3-9391404ad0ed">

**Comment by az** [comment]
@KarolinaTEH https://github.com/ecommerceberlin/site-components/blob/be25be4b29766ff95673f7b646d994a0d4010d1f/src/lib/components/Schedule/ScheduleItemApply.js#L11

check for IFs :)

do we have company assigned to the "masters"?

**Comment by az** [comment]
i will be busy 7.02 (notary, etc) so i would prefer to send out the campaign to the visitors on 6th of Feb

**Comment by az** [comment]
1+2

there is an autoreject ... so it means its "auto" .. its being fired when seats are taken.

https://github.com/eventjuicer/api-components/blob/10abb558e13287692ceb32cfe04a2863f7f52fcf/src/Jobs/Meetups/HandleLTDReject.php#L12

message from mc' organizer is PART OF of substitution data that is sent to sparkpost.... if the data is empty it is just empty... it does not stop anything .....

**Comment by KarolinaTEH** [comment]
6.02 - sure
yes, companies are assigned. all of them are exhibitors, so they were just upgraded with 'masterclasses' ticket
they are visible on: https://ecommerceberlin.com/masterclasses

**Comment by az** [comment]
@KarolinaTEH lack of "limited" data in the profiles = number of seats... i have added in 1 entry and it just works

also remember we have an additional settings setting  **disabledTreshold** (for TEH it was set to 55)

```
 if(disabledTreshold && disabledTreshold > limit && pipeline.length > disabledTreshold){
        return( <MyButton label="workshops.apply.sustained" disabled={true} variant="contained" color="default" />)
    }
```
it disables submissions when there are to many ppl in the pipeline (THAT INFO SHOULD BE PASSED TO THE ORGANIZERS.... "if you do not handle accept/reject you will not get fresh ppl" )

**Comment by KarolinaTEH** [comment]
all clear now, thank you

**Comment by az** [comment]
hour slots: 6 -> 9 (I'll adjust specific times) ✅
