### ISSUE TITLE
(MAINTENANCE) update og_image for speakers

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#394]
example https://res.cloudinary.com/eventjuicer/image/upload/v1697098804/template_teh24_spkr.png

upload to template (mind the dimensions) to eventjuicer cloudinary (top level)

create PR with an update to EBE project settings
settings > speakers > og_template with cloudinary asset id

**Comment by KarolinaTEH** [comment]
thanks, I remember about that. Just waiting for the graphics (should be delivered today)
