### ISSUE TITLE
(TEST) test visitor/vip/masterclasses form options 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#402]
related https://github.com/ecommerceberlin/ecommerceberlin.com/issues/401

request a meeting BUTTON 
/exhibitors/3lpeu?meet (promoninja links) 
/exhibitors/smarketerde?vipcode=66a741738f93e193997d5478013ba16419d20893 
/partners/vip_haendler 
/visit - WidgetVisitorWithVip 
/vip - WidgetRegForm 
company profile - WidgetVisitorNonVip 
masterclasses 
visitor profile update

**Comment by az** [comment]
@KarolinaTEH shall i close it?

**Comment by KarolinaTEH** [comment]
yes, all works
