### ISSUE TITLE
(INFO) masterclasses timeline

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#403]
6.02 - e-mail to Exhibitors (MT)
7.02 - submissions start
7.02 - message to all visitors
12.02 - reminder to all visitors
14.02 - official end of submissions and deadline for reviewing applications
15.02 - logistics info for Exhibitors (MT)
19/20.02 - logistics info for MS attendees (MT)

**Comment by az** [comment]
@KarolinaTEH  

(offtopic:  1 issue = 1 subject…. timeline is sth different than changing the params)

all visitors  = OLD or CURRENT?

i thing TODAY it should be dispatched for CURRENT (to test things etc) ... and tomorrow for OLD

**Comment by az** [comment]
related https://github.com/ecommerceberlin/ecommerceberlin.com/issues/398

**Comment by KarolinaTEH** [comment]
just CURRENT
and MT will take care of the OLD ones if we'll not have enough applications

**Comment by az** [comment]
@KarolinaTEH OK.... i will dispatch it as soon as the translations are fixed 

re OLD ones... we will see. we know how it looked before.
