### ISSUE TITLE
(TRANSLATION) fix untrue information

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#406]
![E-commerce Berlin Expo | Berlin | February, 2024 2024-02-06 12-59-20](https://github.com/ecommerceberlin/ecommerceberlin.com/assets/2198/70b2350e-7cdb-4df9-8f18-37650218f123)

**one can sign up up to 8 sessions (one per each hr).... you can TAKE PART in 3 MC**

**Comment by KarolinaTEH** [comment]
done
