### ISSUE TITLE
(MAINTENANCE) update ticket template

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#410]
SUGGESTED FONT: DM SANS

INPUT

1. Upper half of the page - visitor’s badge

Links to graphics:
[Regular](https://res.cloudinary.com/ecommerceberlin/image/upload/v1707222696/Website/ebe24_regular_ticket_graphic.pdf)
[VIP](https://res.cloudinary.com/ecommerceberlin/image/upload/v1707223862/Website/ebe24_vip_ticket_graphic.pdf) 

Expo partner: ikas ([logo](https://res.cloudinary.com/eventjuicer/image/upload/v1707233687/ikas-logo-03.pdf)) 

2. Middle of the page - text

Print, fold and insert into a badge holder, available on arrival at the event

3. Left bottom corner - text

WELCOME TO THE E-COMMERCE BERLIN EXPO! 

HOW TO USE YOUR BADGE 

To ensure a seamless experience at the event, please follow these instructions for using your badge: 

1. **Print this page** clearly on A4 paper and **bring it with you** to the venue. 
2. Upon arrival, head directly to the entrance to be scanned in. 
3. Badge holders and lanyards will be available at the entrance. 
4. If you lose or forget your badge, visit the registration kiosk for a reprint. Please note that **not having your badge may result in a delay at the entrance.**

STAY CONNECTED!

Follow us on social media and use the official event hashtags when you share. We can't wait to see your posts!

**#EcommerceBerlinExpo2024 #EBE2024 #EcommBerlin**

4. Right bottom corner - text

VENUE

STATION Berlin
Luckenwalder Str. 4-6
10963 Berlin, Germany

OPENING TIME

Thursday, 22nd February 2024, 09:00-18:00

REACHING THE EVENT

To avoid traffic, we **strongly suggest** using public transportation. The closest U-Bahn station, "Gleisdreieck," is available for your convenience. 
Alternatively, if you choose to drive, there's a nearby car park, "Parkhaus Gleisdreieck". Parking fees may apply.

CONTACT

visitors@ecommerceberlin.com

**THANK YOU FOR CHOOSING TO JOIN US!**

**Comment by KarolinaTEH** [comment]
@az i'd be great to have it ready to be sent at the beginning of next week - preferably 12.02

**Comment by KarolinaTEH** [comment]
@az, tickets dispatch should be starting, so could you please let me know when to expect the possibility?

**Comment by az** [comment]
@KarolinaTEH today..... most probably 14:00-15:00 your time

**Comment by KarolinaTEH** [comment]
thanks!

**Comment by az** [comment]
done
