### ISSUE TITLE
(BUG) unwanted video autoplay on mobile browser

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#424]
upon accessing the website through a mobile browser, a video from the header section starts playing automatically (same for TEH and EGA)
video screen:
https://github.com/ecommerceberlin/ecommerceberlin.com/assets/80756258/d92b18a4-4fa4-4d2f-9da0-758d9b39a79f

**Comment by az** [comment]
seems like react/nextjs (outside) problem.... i encourage to disable video on EBE/EGA 

how to disable? just comment //videoSrc in here section in settings

**Comment by az** [comment]
it was mobile-specific feature... "picture in picture" ... now disabled
