### ISSUE TITLE
(IDEA) Division of registration notification types on Slack

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#431]
@az could you divide this 3 types of registration notification on slack? 
- ambassador - ticket id: 2831
- vip - ticket id: 2830
- offer - ticket id: 2753
we've previously discussed that adding 'roles' is not a good solution, but maybe a dedicated channel for each of them would work?

**Comment by az** [comment]
@KarolinaTEH i must dive in slack API details..... i will come back with some ideas

**Comment by KarolinaTEH** [comment]
@az there are 2 more forms on the website, and it got 'quite' messy at the sales channel
new forms:
- report request - ticket id: 2990
- masterclasses application - ticket id: 2782

**Comment by az** [comment]
@KarolinaTEH ok i ve come up with some solution... can u provide slack channel names? 

```
ambassador - ticket id: 2831
vip - ticket id: 2830
offer - ticket id: 2753
report request - ticket id: 2990
masterclasses application - ticket id: 2782
```

**Comment by KarolinaTEH** [comment]
#ambassador_application
#vip_application
#offer_request
#report_request
#mc_application

**Comment by az** [comment]
done... instructions on slack #ecommerceberlin_it
