### ISSUE TITLE
(MAINTENANCE) add HTML verification tag 

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#435]
@az could you please add HTML tag (provided via slack) to EBE website? (to verify ownership and gain access to Google Search Console)

attempts to verify it via GTM, Google Analytics have failed, likely due to the nature of the website (SPA)

documentation for the process if needed: [Verify your site ownership - Google Support](https://support.google.com/webmasters/answer/9008080#html_verification&zippy=%2Cprzes%C5%82anie-pliku-html)

**Comment by az** [comment]
hi, i do not mess with html/template - please provide code for domain verification option

google-site-verification XXXXXXXXXXXXXX

**Comment by KarolinaTEH** [comment]
sure, 
EBE: google-site-verification=b8JsIbxHxwiaZPAqORjEOPZk2s3HRlcu_DX9unmEX1g
EGN: google-site-verification=6fdAKCn7FJF3i8CUbHLSJFhZ94ycdZBDLbTOYpoWyxA

**Comment by KarolinaTEH** [comment]
@az ;)
