### ISSUE TITLE
(MAINTENANCE) change WidgetJurors limit

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommerceberlin.com#443]
@az, here is the updated file:
[WidgetJurors.js.zip](https://github.com/user-attachments/files/16886709/WidgetJurors.js.zip)

(note: limit changed to 30 instead of 20)

**Comment by az** [comment]
hello @KarolinaTEH 
thats not the way to do it.... i am not changing anything in "base library" when expected behaviour can be resolved via local 

use 

<WidgetJurors limit={30} 

or 

limit: 30 in settings (if you pass setting branch/name...)

**Comment by KarolinaTEH** [comment]
PR: https://github.com/ecommerceberlin/ecommerceberlin.com/pull/444
