### ISSUE TITLE
GENERAL - fix the event date in the visitor confirmation email 

### ISSUE THREAD

**Issue by peterecommberlin** [ecommerceberlin/ecommerceberlin.com#58]
We will meet on **24th of February 2022** at STATION Berlin, Luckenwalder Str. 4-6

If you have any questions please do not hesitate to contact us visitors@ecommerceberlin.com

Du hast dich erfolgreich für die E-commerce Berlin Expo 2022 registriert. Wir sehen uns den **24.02.2022** in der STATION Berlin in der Luckenwalder Str. 4-6.

Falls Rückfragen bestehen, dann zögere nicht uns zu fragen unter: visitors@ecommerceberlin.com

regards! Lieben Gruß! E-commerce Berlin Expo Team

**Comment by az** [comment]
updated
