### ISSUE TITLE
confirm or choose other icons for CFP voting categories 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#59]
categories on TEH are identical but if you want to change some icons - put their names in the comment below (resource https://material-ui.com/components/material-icons/)

![20  Targi eHandlu - Warszawa - 20 października 2021 2021-09-08 11-35-18](https://user-images.githubusercontent.com/2198/132485199-9ddd2a80-54ed-4492-9075-51cdf6db7dad.jpg)

**Comment by jprzybylski4** [comment]
If possible please change Logistics icon to: LocalShipping
