### ISSUE TITLE
translations for CFP submission data edit page

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#65]
required by https://github.com/ecommerceberlin/ecommerceberlin.com/issues/53
localise labels below

![E-commerce Berlin Expo  Berlin  February, 2022 2021-09-15 13-55-43](https://user-images.githubusercontent.com/2198/133429235-793d1c59-9185-4173-9782-28587fe5fd8b.jpg)

**Comment by jprzybylski4** [comment]
Done
