### ISSUE TITLE
translate voting pages bullshit

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#72]
![E-commerce Berlin Expo  Berlin  February, 2022 2021-09-16 15-30-45](https://user-images.githubusercontent.com/2198/133621216-c8068cc7-0863-41d2-b2cb-75bb1c4bcf24.jpg)

nothing seems right here

**also "common.votes" needs to be translated**

**Comment by az** [comment]
also please remove "Each Online Voter can participate in the event for free and watch all of the presentations live. Click here to collect your free ticket" as we spoke - this is an anti-pattern.... encouring to register is now part of the voting process ("on voted" behaviour )

**Comment by jprzybylski4** [comment]
updated & changed
