### ISSUE TITLE
translate "on voted" dialog

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#73]
you ask me to remove button but how would you know what to translate @jprzybylski4 ?

![Vote for the presentation Choice to be Tracked Balancing Between Big Data, GDPR and ePrivacy #ecommberlin 2021-09-16 15-38-20](https://user-images.githubusercontent.com/2198/133622512-8ec692e7-c751-44f8-bfb2-6658b5bd0a3a.jpg)

**Comment by jprzybylski4** [comment]
done
