### ISSUE TITLE
translate bad linkedin token dialog

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#74]
![Vote for the presentation Phantom Banking an epayment system with intangible intrinvalue  #ecommberlin 2021-09-16 15-42-37](https://user-images.githubusercontent.com/2198/133623083-ebfd7889-e4a3-419a-bd61-25679ff0b84d.jpg)

this is the dialog that should show up when the saved (in local storage) token is BAD (means OLD) - user should then reconnect with linkedin

**Comment by jprzybylski4** [comment]
Could you please explain? Should the message tell you to log in again?

**Comment by az** [comment]
@jprzybylski4 yes. sth like "Your linkedin session timed out. Please reconnect."

**Comment by jprzybylski4** [comment]
done
