### ISSUE TITLE
fresh list of featured exhibitors

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#80]
some of them are not participating (user will get info about archived profile) it would be better to show current exhibitors (contest prize is now expired i think?)

![E-commerce Berlin Expo | Berlin | February, 2022 2021-09-30 20-21-14](https://user-images.githubusercontent.com/2198/135509913-b5d68eef-4152-4380-bac3-494cff4f9f22.jpg)

**Comment by peterecommberlin** [comment]
1. Shopware
2. JTL-Software
3. Channable
4. Checkout GmbH
5. Allegro 
6. Netgrade
7. Wish
8. Plentymarkets
9. Websale
10. Thras
11. VR Payment
12. PARCEL.ONE

**Comment by az** [comment]
@peterecommberlin checkout - no such company. 
https://ecommerceberlin.com/exhibitors/jtl-softwarecom - archived!!! error or you have not read the issue description? 
(cc @jprzybylski4 )
