### ISSUE TITLE
translate visitor registration form displayed after voting 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommerceberlin.com#81]
![Vote for the presentation 360°-Sicht auf den Kunden_ So schafft Telefónica mit trbo die perfekte Onsite Experience #ecommberlin 2021-10-01 05-25-45](https://user-images.githubusercontent.com/2198/135561248-973a179a-d099-4a17-a496-49cd47c46905.jpg)

**Comment by jprzybylski4** [comment]
done
