### ISSUE TITLE
Incorrect URLs addresses on order page $45$

### ISSUE THREAD

**Issue by peterecommberlin** [ecommerceberlin/ecommerceberlin.com#84]
błędnie podlinkowane adresy do stron
https://order.ecommerceberlin.com/preorder 

- Rules for exhibitors.
- Rules for visitors
- Imprint

**Comment by az** [comment]
updated - future updates via https://pages.ecommerceberlin.com/admin/widget/3421?updated 
@peterecommberlin  @jprzybylski4
