### ISSUE TITLE
Change company URLs $60$

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#86]
- Fynax 
ID: 117011 - etlde - fynaxio
- YouSellWeSend
ID: 117473 - 4elements-gruppede - yousellwesendde
- Kaufland.de
ID: 118901 - real-digitalde - kauflandde
- Bright Data
ID: 119813 - luminatiio - brightdatacom
- Big Buy
ID: 127262 - a4bgroupcom - bigbuyeu
- Price Intelligence
ID: 127550 - parsionatecom - priceintelligencenet
- Pick To Light Systems 
ID: 133477 - ulmahandlingcom - picktolightsystemscom

**Comment by az** [comment]
```
/exhibitors/etlde -> /exhibitors/fynaxio
/exhibitors/4elements-gruppede -> /exhibitors/yousellwesendde
/exhibitors/real-digitalde -> /exhibitors/kauflandde
/exhibitors/luminatiio -> /exhibitors/brightdatacom
/exhibitors/a4bgroupcom -> /exhibitors/bigbuyeu
/exhibitors/parsionatecom -> /exhibitors/priceintelligencenet
/exhibitors/ulmahandlingcom -> /exhibitors/picktolightsystemscom
```

**Comment by az** [comment]
67b932b144c16710c5e92c36a67b3bca6faec237
