### ISSUE TITLE
Add banner to EGA page

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#97]
Same as with issue #89 on EGA repo (https://github.com/ecommerceberlin/ecommercegermanyawards.com/issues/89)
I'd like to direct traffic from EBE website so that the users can vote. 

Two same ideas here as well:

1. The best way would be to show part of the screenshot of the EGA/vote website. 
2. If not possible I will provide the banners

**Comment by az** [comment]
can you please provide me with traffic stats of "directed" traffic we achieved during previous edition of EGA (i remember we had such a banner) - how many directed people voted?

**Comment by az** [comment]
please provide banners ... i will put one somewhere after most crucial elements 

btw: too boost visitor regs (As the sales process is almost done) i will also put reg form a bit higher :)

![E-commerce Berlin Expo | Berlin | February, 2022 2021-12-01 19-22-24](https://user-images.githubusercontent.com/2198/144291776-4a745077-cf1c-4db1-92a0-fa2edb017265.jpg)

**Comment by az** [comment]
in addition to banners - can you provide valid UTMs for better monitoring of directed traffic?

**Comment by jprzybylski4** [comment]
UTM -  https://ecommerceberlin.com/visit?utm_source=EGAwards&utm_medium=banner_profile&utm_campaign=ega_banner_voting

**Comment by jprzybylski4** [comment]
banner from EBE - EBV stats:
https://share.getcloudapp.com/E0uKQKo7

**Comment by jprzybylski4** [comment]
UTM
https://ecommercegermanyawards.com/vote?utm_source=ecommerceberlin&utm_medium=top_banner&utm_campaign=ebe_banner_voting

**Comment by jprzybylski4** [comment]
banners:
https://drive.google.com/drive/folders/13Fobi415IqSXMAEO-QYLTS-0vqoME3Jv?usp=sharing

**Comment by az** [comment]
@jprzybylski4 thx for complete info. i will try to handle that in 2-3 days.

**Comment by az** [comment]
@jprzybylski4 as you can see the "recommended way of doing things" works great so i am closing this shitty task
