### ISSUE TITLE
Enable agenda widget on the website 

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommerceberlin.com#98]
We already have 90% of the agenda
It would be great if we could enable tags as well - issue #43 
Also, we might need to be able to add 2 tags to a presentation - if possible

**Comment by az** [comment]
@jprzybylski4 there is nothing for me to do... issue is invalid 

https://pages.ecommerceberlin.com/admin/filtered?tags=speaker 90%? ......also no time, no venue... no basic info required for widget to work
